In [50]:
import pandas as pd
import os
import time
import requests
import spotipy
from dotenv import load_dotenv
from sentence_transformers import SentenceTransformer
from spotipy.oauth2 import SpotifyClientCredentials
pd.set_option('display.max_columns', None)

In [51]:
load_dotenv()
client_id = os.getenv('SPOTIPY_CLIENT_ID')
client_secret = os.getenv('SPOTIPY_CLIENT_SECRET')
sp = spotipy.Spotify(auth_manager=SpotifyClientCredentials(
    client_id=client_id, 
    client_secret=client_secret
))

In [52]:
semantic_data = pd.read_csv('C:/Users/maxph/OneDrive/Desktop/DS3-CLARIFY/data/training_data/processed_lyrics_features.csv')
semantic_data

,SONG_ID,Clean_Lyrics,Word_Count,Unique_Word_Count,Repetition_Score,Average_Line_Length,Vocabulary_Diversity,Title_Repetition,Explicit_Word_Count,Sentiment_Score,Positive_Score,Negative_Score,Emotional_Intensity
0,7j5TIXPi0cCbSSqItmbyZy,what are you looking at?\r\n\r\nstrike a pose\...,455,185,0.5934,5.9091,0.4066,34,0,0.9753,0.072,0.026,0.9753
1,0yp3TvJNlG50Q4tAHWNCRm,words like violence\r\nbreak the silence\r\nco...,141,56,0.6028,3.8108,0.3972,1,0,-0.9701,0.059,0.187,0.9701
2,3XVozq1aeqsJwpXrEZrDJ9,"yo vip, let's kick it\r\nice, ice baby\r\nice,...",611,291,0.5237,6.9432,0.4763,0,2,-0.4058,0.099,0.096,0.4058
3,7EsjkelQuoUlJXEw7SeVV4,aaow!\r\n\r\naaow!\r\n\r\ni took my baby on a ...,364,151,0.5852,5.9672,0.4148,5,0,0.9690,0.166,0.111,0.9690
4,5ghIJDpPoe3CfHMGu71E6T,"load up on guns, bring your friends\r\nit's fu...",253,91,0.6403,5.1633,0.3597,0,0,-0.9119,0.136,0.192,0.9119
...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,5fZJQrFKWQLb7FpJXZ1g7K,my baby want a birkin\r\nshe's been telling me...,358,126,0.6480,7.9556,0.3520,0,2,0.8327,0.061,0.033,0.8327
104,6AI3ezQ4o3HUoP6Dhudph3,"psst, i see dead people\r\n(mustard on the bea...",900,413,0.5411,8.8235,0.4589,12,31,-0.5519,0.092,0.097,0.5519
105,2plbrEY59IikOBgBGLjaoe,"(ooh, ooh)\r\n\r\ni, i just woke up from a dre...",293,89,0.6962,7.9189,0.3038,3,0,0.9765,0.167,0.094,0.9765
106,2CGNAOSuO1MEFCbBRgUzjd,"(if this world were mine)\r\n\r\nhey, roman nu...",414,170,0.5894,9.0000,0.4106,0,0,0.9555,0.118,0.086,0.9555
107,2RkZ5LkEzeHGRsmDqKwmaJ,"they say, ""the holy water's watered down\r\nan...",378,142,0.6243,7.1321,0.3757,7,0,-0.6229,0.098,0.108,0.6229

In [53]:
model = SentenceTransformer('all-MiniLM-L6-v2')

# 3. Generate embeddings for your clean lyrics column
# Ensure your lyrics column has no missing values (NaN) before running this
lyrics_list = semantic_data['Clean_Lyrics'].fillna("").tolist()
print("Generating embeddings... this might take a moment.")
embeddings = model.encode(lyrics_list, show_progress_bar=True)

# 4. Create columns for the embeddings in a new DataFrame
# The MiniLM model outputs a 384-dimensional vector, creating BERT_Embedding_0 to BERT_Embedding_383
embedding_data = pd.DataFrame(
    embeddings, 
    columns=[f'BERT_Embedding_{i}' for i in range(embeddings.shape[1])]
)

# 5. Concatenate the original features with the new embedding features
final_data = pd.concat([semantic_data, embedding_data], axis=1)
final_data

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 8022.38it/s]

Generating embeddings... this might take a moment.

Batches: 100%|██████████| 4/4 [00:02<00:00,  1.88it/s]

,SONG_ID,Clean_Lyrics,Word_Count,Unique_Word_Count,Repetition_Score,Average_Line_Length,Vocabulary_Diversity,Title_Repetition,Explicit_Word_Count,Sentiment_Score,Positive_Score,Negative_Score,Emotional_Intensity,BERT_Embedding_0,BERT_Embedding_1,BERT_Embedding_2,BERT_Embedding_3,BERT_Embedding_4,BERT_Embedding_5,BERT_Embedding_6,BERT_Embedding_7,BERT_Embedding_8,BERT_Embedding_9,BERT_Embedding_10,BERT_Embedding_11,BERT_Embedding_12,BERT_Embedding_13,BERT_Embedding_14,BERT_Embedding_15,BERT_Embedding_16,BERT_Embedding_17,BERT_Embedding_18,BERT_Embedding_19,BERT_Embedding_20,BERT_Embedding_21,BERT_Embedding_22,BERT_Embedding_23,BERT_Embedding_24,BERT_Embedding_25,BERT_Embedding_26,BERT_Embedding_27,BERT_Embedding_28,BERT_Embedding_29,BERT_Embedding_30,BERT_Embedding_31,BERT_Embedding_32,BERT_Embedding_33,BERT_Embedding_34,BERT_Embedding_35,BERT_Embedding_36,BERT_Embedding_37,BERT_Embedding_38,BERT_Embedding_39,BERT_Embedding_40,BERT_Embedding_41,BERT_Embedding_42,BERT_Embedding_43,BERT_Embedding_44,BERT_Embedding_45,BERT_Embedding_46,BERT_Embedding_47,BERT_Embedding_48,BERT_Embedding_49,BERT_Embedding_50,BERT_Embedding_51,BERT_Embedding_52,BERT_Embedding_53,BERT_Embedding_54,BERT_Embedding_55,BERT_Embedding_56,BERT_Embedding_57,BERT_Embedding_58,BERT_Embedding_59,BERT_Embedding_60,BERT_Embedding_61,BERT_Embedding_62,BERT_Embedding_63,BERT_Embedding_64,BERT_Embedding_65,BERT_Embedding_66,BERT_Embedding_67,BERT_Embedding_68,BERT_Embedding_69,BERT_Embedding_70,BERT_Embedding_71,BERT_Embedding_72,BERT_Embedding_73,BERT_Embedding_74,BERT_Embedding_75,BERT_Embedding_76,BERT_Embedding_77,BERT_Embedding_78,BERT_Embedding_79,BERT_Embedding_80,BERT_Embedding_81,BERT_Embedding_82,BERT_Embedding_83,BERT_Embedding_84,BERT_Embedding_85,BERT_Embedding_86,BERT_Embedding_87,BERT_Embedding_88,BERT_Embedding_89,BERT_Embedding_90,BERT_Embedding_91,BERT_Embedding_92,BERT_Embedding_93,BERT_Embedding_94,BERT_Embedding_95,BERT_Embedding_96,BERT_Embedding_97,BERT_Embedding_98,BERT_Embedding_99,BERT_Embedding_100,BERT_Embedding_101,BERT_Embedding_102,BERT_Embedding_103,BERT_Embedding_104,BERT_Embedding_105,BERT_Embedding_106,BERT_Embedding_107,BERT_Embedding_108,BERT_Embedding_109,BERT_Embedding_110,BERT_Embedding_111,BERT_Embedding_112,BERT_Embedding_113,BERT_Embedding_114,BERT_Embedding_115,BERT_Embedding_116,BERT_Embedding_117,BERT_Embedding_118,BERT_Embedding_119,BERT_Embedding_120,BERT_Embedding_121,BERT_Embedding_122,BERT_Embedding_123,BERT_Embedding_124,BERT_Embedding_125,BERT_Embedding_126,BERT_Embedding_127,BERT_Embedding_128,BERT_Embedding_129,BERT_Embedding_130,BERT_Embedding_131,BERT_Embedding_132,BERT_Embedding_133,BERT_Embedding_134,BERT_Embedding_135,BERT_Embedding_136,BERT_Embedding_137,BERT_Embedding_138,BERT_Embedding_139,BERT_Embedding_140,BERT_Embedding_141,BERT_Embedding_142,BERT_Embedding_143,BERT_Embedding_144,BERT_Embedding_145,BERT_Embedding_146,BERT_Embedding_147,BERT_Embedding_148,BERT_Embedding_149,BERT_Embedding_150,BERT_Embedding_151,BERT_Embedding_152,BERT_Embedding_153,BERT_Embedding_154,BERT_Embedding_155,BERT_Embedding_156,BERT_Embedding_157,BERT_Embedding_158,BERT_Embedding_159,BERT_Embedding_160,BERT_Embedding_161,BERT_Embedding_162,BERT_Embedding_163,BERT_Embedding_164,BERT_Embedding_165,BERT_Embedding_166,BERT_Embedding_167,BERT_Embedding_168,BERT_Embedding_169,BERT_Embedding_170,BERT_Embedding_171,BERT_Embedding_172,BERT_Embedding_173,BERT_Embedding_174,BERT_Embedding_175,BERT_Embedding_176,BERT_Embedding_177,BERT_Embedding_178,BERT_Embedding_179,BERT_Embedding_180,BERT_Embedding_181,BERT_Embedding_182,BERT_Embedding_183,BERT_Embedding_184,BERT_Embedding_185,BERT_Embedding_186,BERT_Embedding_187,BERT_Embedding_188,BERT_Embedding_189,BERT_Embedding_190,BERT_Embedding_191,BERT_Embedding_192,BERT_Embedding_193,BERT_Embedding_194,BERT_Embedding_195,BERT_Embedding_196,BERT_Embedding_197,BERT_Embedding_198,BERT_Embedding_199,BERT_Embedding_200,BERT_Embedding_201,BERT_Embedding_202,BERT_Embedding_203,BERT_Embedding_204,BERT_Embedding_205,BERT_Embedding_206,BERT_Embedding_207,BERT_Embedding_208,BERT_Embedding_209,BERT_Embedding_210,BERT_Embedding_211,BERT_Embedding_212,BERT_Embedding_213,BERT_Embedding_214,BERT_Embedding_215,BERT_Embedding_216,BERT_Embedding_217,BERT_Embedding_218,BERT_Embedding_219,BERT_Embedding_220,BERT_Embedding_221,BERT_Embedding_222,BERT_Embedding_223,BERT_Embedding_224,BERT_Embedding_225,BERT_Embedding_226,BERT_Embedding_227,BERT_Embedding_228,BERT_Embedding_229,BERT_Embedding_230,BERT_Embedding_231,BERT_Embedding_232,BERT_Embedding_233,BERT_Embedding_234,BERT_Embedding_235,BERT_Embedding_236,BERT_Embedding_237,BERT_Embedding_238,BERT_Embedding_239,BERT_Embedding_240,BERT_Embedding_241,BERT_Embedding_242,BERT_Embedding_243,BERT_Embedding_244,BERT_Embedding_245,BERT_Embedding_246,BERT_Embedding_247,BERT_Embedding_248,BERT_Embedding_249,BERT_Embedding_250,BERT_Embedding_251,BERT_Embedding_252,BERT_Embedding_253,BERT_Embedding_254,BERT_Embedding_255,BERT_Embedding_256,BERT_Embedding_257,BERT_Embedding_258,BERT_Embedding_259,BERT_Embedding_260,BERT_Embedding_261,BERT_Embedding_262,BERT_Embedding_263,BERT_Embedding_264,BERT_Embedding_265,BERT_Embedding_266,BERT_Embedding_267,BERT_Embedding_268,BERT_Embedding_269,BERT_Embedding_270,BERT_Embedding_271,BERT_Embedding_272,BERT_Embedding_273,BERT_Embedding_274,BERT_Embedding_275,BERT_Embedding_276,BERT_Embedding_277,BERT_Embedding_278,BERT_Embedding_279,BERT_Embedding_280,BERT_Embedding_281,BERT_Embedding_282,BERT_Embedding_283,BERT_Embedding_284,BERT_Embedding_285,BERT_Embedding_286,BERT_Embedding_287,BERT_Embedding_288,BERT_Embedding_289,BERT_Embedding_290,BERT_Embedding_291,BERT_Embedding_292,BERT_Embedding_293,BERT_Embedding_294,BERT_Embedding_295,BERT_Embedding_296,BERT_Embedding_297,BERT_Embedding_298,BERT_Embedding_299,BERT_Embedding_300,BERT_Embedding_301,BERT_Embedding_302,BERT_Embedding_303,BERT_Embedding_304,BERT_Embedding_305,BERT_Embedding_306,BERT_Embedding_307,BERT_Embedding_308,BERT_Embedding_309,BERT_Embedding_310,BERT_Embedding_311,BERT_Embedding_312,BERT_Embedding_313,BERT_Embedding_314,BERT_Embedding_315,BERT_Embedding_316,BERT_Embedding_317,BERT_Embedding_318,BERT_Embedding_319,BERT_Embedding_320,BERT_Embedding_321,BERT_Embedding_322,BERT_Embedding_323,BERT_Embedding_324,BERT_Embedding_325,BERT_Embedding_326,BERT_Embedding_327,BERT_Embedding_328,BERT_Embedding_329,BERT_Embedding_330,BERT_Embedding_331,BERT_Embedding_332,BERT_Embedding_333,BERT_Embedding_334,BERT_Embedding_335,BERT_Embedding_336,BERT_Embedding_337,BERT_Embedding_338,BERT_Embedding_339,BERT_Embedding_340,BERT_Embedding_341,BERT_Embedding_342,BERT_Embedding_343,BERT_Embedding_344,BERT_Embedding_345,BERT_Embedding_346,BERT_Embedding_347,BERT_Embedding_348,BERT_Embedding_349,BERT_Embedding_350,BERT_Embedding_351,BERT_Embedding_352,BERT_Embedding_353,BERT_Embedding_354,BERT_Embedding_355,BERT_Embedding_356,BERT_Embedding_357,BERT_Embedding_358,BERT_Embedding_359,BERT_Embedding_360,BERT_Embedding_361,BERT_Embedding_362,BERT_Embedding_363,BERT_Embedding_364,BERT_Embedding_365,BERT_Embedding_366,BERT_Embedding_367,BERT_Embedding_368,BERT_Embedding_369,BERT_Embedding_370,BERT_Embedding_371,BERT_Embedding_372,BERT_Embedding_373,BERT_Embedding_374,BERT_Embedding_375,BERT_Embedding_376,BERT_Embedding_377,BERT_Embedding_378,BERT_Embedding_379,BERT_Embedding_380,BERT_Embedding_381,BERT_Embedding_382,BERT_Embedding_383
0,7j5TIXPi0cCbSSqItmbyZy,what are you looking at?\r\n\r\nstrike a pose\...,455,185,0.5934,5.9091,0.4066,34,0,0.9753,0.072,0.026,0.9753,0.032455,-0.020406,0.047048,0.004001,0.008487,0.009719,0.078765,-0.053172,-0.002942,-0.013091,-0.071279,0.019455,0.037108,-0.073128,0.040437,0.007649,0.051440,0.133707,-0.064686,0.092724,-0.015325,-0.039035,-0.078431,0.074520,-0.120340,0.061437,-0.025690,-0.063843,-0.044168,-0.033287,0.003789,0.077287,-0.027463,0.047424,-0.005885,0.081505,-0.067823,0.022822,-0.000809,0.090300,-0.009845,-0.030896,-0.013245,0.018173,0.061038,-0.052164,0.049487,0.009944,0.016456,0.008449,-0.091071,-0.042638,-0.037861,0.076814,0.022306,0.030891,0.041414,0.006084,0.025041,0.031125,-0.005604,-0.081221,-0.025031,0.028449,-0.002614,-0.034486,0.068054,0.056171,-0.034595,0.058267,0.023375,-0.117891,0.003391,0.065915,0.057882,0.092576,0.010887,-0.085392,-0.043355,-0.005817,0.015949,-0.008401,-0.035409,-0.061885,-0.063872,0.012390,-0.008102,0.034025,0.055166,-0.061142,-0.121393,0.041138,-0.105965,-0.089579,0.076957,-0.051344,-0.011547,-0.049339,-0.014422,0.037912,0.075117,-0.000107,0.052137,0.018820,-0.010957,-0.102126,0.087031,0.075581,0.014546,0.004803,-0.019055,-0.017605,0.019897,-0.013003,0.066464,-0.027534,0.013873,0.000055,0.044647,0.076714,-0.025768,-0.032804,-0.038597,-0.035812,-0.184865,0.008755,0.041734,-1.596165e-33,0.031315,0.041095,0.083099,0.088208,0.033834,-0.040240,-0.053107,-0.001964,-0.033040,0.086553,0.077468,-0.025645,-0.025536,0.083302,0.051197,-0.021958,-0.060891,-0.071541,0.052171,0.054887,0.018884,0.000913,-0.027546,-0.048034,-0.023387,0.047801,0.004269,-0.048233,-0.130753,-0.016313,0.033840,0.078249,0.042280,0.012024,-0.047288,-0.051203,-0.000989,0.023222,0.042546,-0.023236,-0.056710,0.017391,0.019378,0.002825,0.023471,0.101532,-0.013757,0.015938,0.043624,0.052646,0.052153,-0.049725,0.003291,-0.011615,-0.014069,-0.034340,-0.063538,-0.004348,0.077925,0.015198,0.027892,-0.035320,-0.037950,0.011477,0.057404,0.025543,-0.018115,-0.080954,0.053528,0.044077,-0.088820,-0.029560,-0.026807,0.045177,0.044155,-0.019539,-0.030136,-0.095866,-0.035175,0.065632,-0.023688,0.063422,-0.038833,0.084057,0.067575,-0.017991,0.033695,-0.013001,-0.034643,0.012438,-0.122378,0.064797,0.040184,-0.072434,-0.033459,6.991164e-34,0.119993,0.053709,0.058824,0.106079,0.094937,-0.003747,-0.030255,-0.015294,0.033511,0.033149,-0.026710,-0.076292,-0.029901,-0.060213,0.054843,-0.004996,-0.008451,0.028729,-0.071572,0.070094,-0.056793,0.033849,-0.031708,0.001521,-0.136645,-0.001287,0.029200,0.108253,0.033379,0.002297,0.007357,-0.003578,0.021689,-0.002958,-0.045004,0.055214,0.003491,-0.029228,-0.108438,0.020073,-0.086846,-0.053673,-0.020040,0.003990,0.001854,-0.078725,-0.028377,0.094136,-0.021642,0.030651,0.047013,-0.015046,-0.010781,0.009470,0.019455,-0.050176,0.038069,-0.046768,0.005775,0.020031,0.014121,0.048385,-0.057133,-0.022932,-0.033856,-0.006737,-0.022277,-0.019067,-0.058953,0.084408,-0.048655,0.004173,-0.021381,-0.001301,-0.080785,-0.041075,0.040742,-0.023276,-0.036696,-0.005443,0.012842,-0.058568,-0.022582,-0.024226,0.083300,0.131421,-0.021194,0.054174,-0.023625,-0.027411,-0.024811,0.031176,-0.033703,0.006982,-0.029947,-5.502888e-08,-0.035554,-0.018047,0.012605,0.007770,-0.045484,0.045097,0.019847,-0.050419,0.081992,-0.020658,0.032286,0.001018,0.053660,0.069895,-0.023172,-0.052519,-0.018580,0.042654,-0.047563,-0.001906,-0.000603,-0.022962,-0.001281,-0.094432,0.009686,-0.024482,0.043419,-0.014519,-0.057434,0.028747,0.012730,0.005823,0.021476,-0.013217,-0.074273,-0.027148,0.107083,-0.034320,-0.018001,-0.044997,-0.024483,0.045560,0.078554,-0.010164,-0.132855,-0.073192,0.092294,0.015037,-0.004141,0.021168,0.001270,-0.071914,0.012204,0.001284,0.020541,0.003309,-0.078053,0.120999,0.010399,0.037722,-0.001642,-0.026586,-0.028940,-0.081022
1,0yp3TvJNlG50Q4tAHWNCRm,words like violence\r\nbreak the silence\r\nco...,141,56,0.6028,3.8108,0.3972,1,0,-0.9701,0.059,0.187,0.9701,0.011486,0.055678,0.075591,0.032436,0.043046,0.006275,0.029578,-0.070303,0.090080,-0.020128,-0.017440,-0.008217,0.032229,-0.025745,0.028203,0.073453,0.040940,0.009700,-0.128235,0.074903,-0.000771,0.160453,0.011514,-0.033375,-0.100990,0.034931,-0.054715,0.021306,0.052188,-0.036338,0.028748,-0.023675,0.068130,0.072311,0.057593,-0.024928,-0.056556,0.024365,-0.015452,-0.064875,-0.010226,0.004540,-0.035841,-0.057581,0.002122,-0.022570,-0.053218,-0.050524,0.056586,-0.027143,-0.053845,-0.050441,-0.031229,0.062528,0.011583,-0.011309,0.020230,0.058545,-0.024287,0.020442,-0.071611,0.000862,0.041271,-0.003093,0.017047,0.022338,0.068055,0.025522,-0.030435,0.095181,-0.064940,0.078670,0.014507,0.048324,-0.056349,0.010231,-0.026945,-0.014658,0.030454,0.071041,-0.102274,-0.028114,-0.031926,-0.046099,-0.031997,0.017985,0.038666,-0.080619,0.041674,-0.034820,-0.030591,-0.051617,0.016717,0.015406,0.038768,-0.048808,-0.064022,-0.049230,-0.140271,0.016680,0.022267,-0.055569,0.015672,-0.031862,0.005947,-0.021256,-0.067529,-0.011341,-0.098719,0.017855,-0.035456,-0.056807,-0.007026,-0.063567,-0.019761,-0.050275,0.042233,-0.019927,0.046496,0.083888,-0.099346,-0.016996,-0.102280,0.122343,-0.083292,-0.103001,-0.014288,9.391342e-33,-0.030236,-0.014698,-0.049001,-0.037633,-0.014089,0.006251,-0.000482,-0.020301,-0.000851,-0.046103,-0.004613,0.030294,0.052291,0.005909,0.039801,-0.036535,0.060438,-0.006479,0.043777,0.034962,-0.067480,0.054476,0.010524,0.012490,-0.111320,-0.014005,0.033302,-0.000404,-0.015254,0.019825,-0.022761,-0.014916,0.055637,-0.042979,0.034041,0.011702,0.018476,0.048066,-0.060992,-0.006794,-0.091921,0.065692,0.007113,-0.024092,-0.000264,0.015957,-0.044684,0.056109,-0.042673,0.010507,0.021789,-0.013798,0.019426,0.072324,-0.049066,0.030382,-0.081330,0.001630,0.027570,0.010127,-0.006011,-0.096573,0.105082,-0.032955,0.039346,-0.028263,-0.032258,-0.022417,-0.054938,-0.009202,-0.070878,-0.000849,0.015189,0.036289,0.016895,-0.053277,0.079018,-0.020212,0.051497,0.051766,-0.007298,0.018302,0.011726,0.048903,0.073822,-0.165851,0.043359,-0.113607,-0.012555,0.054400,-0.028385,0.049033,0.044523,-0.124189,-0.090182,-9.512260e-33,0.088647,0.014434,0.026938,0.096548,0.012864,0.022211,-0.108879,-0.001992,0.038920,0.061945,0.022199,-0.055897,-0.030457,0.004811,0.007227,-0.021878,0.085267,-0.023046,0.069206,0.002620,-0.027565,0.114480,0.054738,-0.007065,0.051997,-0.013626,0.040532,0.009857,-0.018044,0.055344,0.001256,-0.008028,-0.107962,0.084266,-0.000120,-0.064939,-0.008950,0.111680,-0.007110,-0.081622,-0.072894,-0.037241,-0.101109,0.019739,-0.025506,-0.078501,0.021953,0.034734,0.000428,0.080253,0.059408,0.016013,0.059821,0.017186,-0.020471,-0.034730,0.037588,-0.066542,-0.059206,-0.064309,0.025524,0.024705,-0.091181,0.014575,0.035787,0.020838,0.011203,-0.076292,-0.077753,-0.075606,-0.019650,-0.037182,-0.024602,0.027518,-0.004343,0.073040,0.007569,-0.135937,-0.047444,-0.019299,0.024703,-0.019832,-0.006188,0.055710,-0.036011,-0.021093,-0.042780,0.057717,-0.043677,0.042057,0.066487,-0.033996,0.048882,0.021766,-0.007663,-5.020267e-08,-0.031440,-0.010205,-0.078843,-0.032171,-0.018418,0.020683,0.050208,-0.082802,-0.006502,0.027251,0.075664,0.044662,-0.034271,0.039922,-0.051561,0.026508,0.066552,-0.075951,-0.029366,-0.061914,-0.049594,0.026766,-0.007410,-0.043432,-0.000841,0.062702,0.005938,-0.015358,-0.060144,0.016761,0.092963,-0.039684,0.022272,0.011419,-0.029063,0.014182,-0.079627,0.022213,-0.026964,0.052969,-0.055489,0.069675,0.109019,0.015625,-0.020509,-0.002770,0.028077,0.003264,-0.010883,0.009590,-0.007325,0.059645,0.014087,-0.003961,0.031227,0.083545,0.111336,0.024155,-0.043967,0.036285,0.126693,0.008918,0.032970,-0.058457
2,3XVozq1aeqsJwpXrEZrDJ9,"yo vip, let's kick it\r\nice, ice baby\r\nice,...",611,291,0.5237,6.9432,0.4763,0,2,-0.4058,0.099,0.096,0.4058,-0.017920,-0.086241,0.014640,-0.053646,0.002245,0.016595,0.097720,-0.000657,0.033837,-0.039879,-0.051686,0.001328,-0.004426,-0.069052,-0.012947,0.051166,0.106182,0.034545,-0.045132,-0.005664,-0.023144,-0.061191,-0.024245,-0.002859,-0.101556,0.127012,-0.013064,0.034172,-0.021204,-0.046726,0.022053,0.061661,-0.028114,-0.050369,0.039745,0.003046,-0.066820,0.044128,0.003521,-0.003863,0.116545,0.022383,0.006916,0.007439,-0.031531,0.007265,-0.058094,-0.112379,0.003274,-0.017719,-0.056203,-0.071373,0.093495,0.123981,0.017068,0.029442,0.004515,0.056165,0.036337,0.010392,-0.071753,0.018914,0.016088,-0.009328,0.025819,0.021147,0.041295,0.055982,-0.020992,0.044069,-0.049347,0.007492,0.018437,0.053076,0.001342,0.059259,-0.096408,-0.103990,-0.000042,0.013704,0.025261,-0.013888,-0.048117,-0.140350,-0.085618,-0.021572,0.027435,0.018309,0.057500,-0.027584,-0.086109,0.078736,0.008465,-0.047638,0.038825,-0.017437,-0.029569,-0.042829,-0.031186,0.046128,0.069672,0.015531,-0.030232,-0.058379,0.072637,-0.035036,0.014856,0.044105,-0.018689,0.057792,-0.038566,0.011480,0.018758,-0.026458,0.091200,-0.005113,0.016596,0.083705,-0.048866,-0.068223,0.009045,0.026311,-0.017271,0.073583,-0.002896,-0.063736,-0.043466,1.012474e-33,0.002597,0.035429,-0.052273,0.044362,0.176471,-0.046336,0.024464,0.024610,-0.015078,0.128970,0.016027,-0.045383,-0.022750,0.018093,0.026507,-0.026501,-0.062778,-0.066104,-0.059856,0.003340,-0.075413,-0.040468,0.001676,0.084877,-0.031949,0.057115,-0.015949,0.027386,0.076528,-0.005844,-0.042377,0.001471,-0.046613,-0.004415,-0.008213,0.011500,0.023495,0.023401,-0.100222,-0.025482,-0.052881,-0.017490,-0.041842,0.020891,-0.041566,0.049618,-0.049101,0.010928,-0.011531,-0.024508,-0.006756,-0.011801,-0.004187,0.011147,-0.009249,0.023391,0.011149,0.072754,-0.004109,-0.019918,0.007991,-0.058438,-0.061489,-0.035045,0.008651,0.045643,-0.036890,-0.020993,0.102283,-0.042418,0.012982,-0.007044,-0.046839,-0.017781,0.060386,-0.001810,-0.041465,-0.064650,-0.003836,-0.007742,-0.001790,0.007972,-0.067231,0.077210,-0.050628,-0.080453,0.036039,-0.004257,-0.019003,0.041884,-0.147805,-0.006154,0.085166,0.022090,-0.038786,5.361555e-35,0.096663,0.027482,0.023940,0.097885,0.130081,-0.029715,-0.008443,-0.029465,0.073480,-0.057372,-0.002125,-0.072550,-0.047793,0.020884,0.090259,-0.062591,-0.057752,0.120598,0.059889,0.095144,-0.054260,0.058768,-0.044323,0.060753,-0.012053,0.071484,0.053098,0.077138,0.048028,0.085839,0.002645,0.041035,-0.027310,-0.092008,-0.033877,0.053695,-0.001819,-0.056945,-0.147183,-0.050628,-0.016193,-0.048099,-0.056560,0.054563,-0.042525,0.031356,0.011355,0.054455,0.003691,0.092703,0.046037,-0.019353,-0.051784,0.051369,-0.028509,-0.045694,-0.007164,0.019941,-0.029418,-0.007408,0.015998,0.034212,-0.004100,-0.012715,0.042361,0.002064,0.019899,0.000960,0.066042,0.007866,0.017348,0.097081,-0.045790,-0.012355,-0.011734,-0.049529,-0.030616,-0.094142,0.041868,-0.056254,0.006418,0.043038,-0.047118,0.043179,0.032455,0.032522,0.003540,0.010461,-0.092233,-0.009524,0.097812,-0.010473,-0.045452,0.052411,-0.012110,-5.299156e-08,0.030767,0.051519,-0.059258,0.034144,0.104555,-0.018169,-0.031940,0.004140,-0.019747,-0.021741,0.083270,-0.002511,0.080802,0.090133,-0.017988,0.036041,-0.033757,0.039042,-0.056004,-0.038465,-0.050435,0.048118,0.037691,-0.077663,-0.013950,-0.033296,0.034903,0.048036,0.009611,0.043075,-0.004657,0.015421,-0.009871,0.002431,0.034920,-0.065050,-0.022652,-0.035385,0.022374,-0.011935,-0.028381,0.080881,0.004241,-0.007524,-0.074608,-0.112243,-0.019402,0.018035,0.007090,0.078047,-0.021099,-0.024169,-0.002411,-0.007737,0.112197,0.003849,-0.033860,0.086991,-0.081059,0.022062,-0.010722,0.047732,0.052936,-0.123840

In [54]:
feature_data = pd.read_csv('C:/Users/maxph/OneDrive/Desktop/DS3-CLARIFY/data/training_data/theme_lyrics_features.csv')
feature_data

,Song Title,Artist,Release_Year,Reviewer,Violence,Heartbreak,Partying,Drugs,Sex,Self-Empowerment,Success,Hope,Celebration,Coming_Of_Age,Loneliness,Struggle,Love,Friendship,Traveling
0,Vogue,Madonna,1990,Sunny,0.0,0.0,4.0,0.0,0.0,9.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Black or White,Michael Jackson,1991,Sunny,0.0,0.0,0.0,0.0,0.0,4.0,0.0,1.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0
2,C.R.E.A.M.,Wu-Tang Clan,1993,Sunny,5.0,0.0,0.0,7.0,0.0,3.0,5.0,3.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0
3,Wonderwall,Oasis,1995,Sunny,0.0,1.0,0.0,0.0,0.0,6.0,0.0,10.0,0.0,0.0,0.0,0.0,10.0,2.0,0.0
4,Don't Speak,No Doubt,1996,Sunny,0.0,10.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,7.0,5.0,10.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,Old Town Road,"Lil Nas X, Billy Ray Cyrus",2019,Dilraj,0.0,0.0,5.0,2.0,2.0,7.0,6.0,5.0,5.0,3.0,0.0,3.0,2.0,2.0,5.0
104,WAP,"Cardi B, Megan Thee Stallion",2020,Dilraj,1.0,0.0,7.0,0.0,10.0,8.0,6.0,2.0,5.0,0.0,0.0,2.0,2.0,2.0,0.0
105,Anti-Hero,Taylor Swift,2022,Dilraj,0.0,4.0,0.0,0.0,0.0,3.0,0.0,2.0,0.0,4.0,7.0,6.0,3.0,0.0,0.0
106,Not Like Us,Kendrick Lamar,2024,Dilraj,7.0,2.0,4.0,0.0,2.0,8.0,5.0,2.0,2.0,2.0,0.0,5.0,0.0,2.0,0.0
107,Ordinary,Alex Warren,2025,Dilraj,0.0,8.0,0.0,0.0,0.0,3.0,0.0,4.0,0.0,5.0,7.0,7.0,5.0,2.0,0.0

In [55]:
def fetch_spotify_id(row):
    # Convert to string in case of missing data (NaN)
    song = str(row['Song Title']) 
    artist = str(row['Artist'])
    
    # Format the query specifically for the Spotify search engine
    query = f"track:{song} artist:{artist}"
    
    try:
        # Search for 1 track matching the query
        results = sp.search(q=query, type='track', limit=1)
        items = results['tracks']['items']
        
        # If the list is not empty, extract the ID
        if items:
            return items[0]['id']
        else:
            print(f"No match found for: {song} by {artist}")
            return None
            
    except Exception as e:
        print(f"API Error fetching {song}: {e}")
        return None

In [56]:
feature_data['SONG_ID'] = feature_data.apply(fetch_spotify_id, axis=1)
feature_data

,Song Title,Artist,Release_Year,Reviewer,Violence,Heartbreak,Partying,Drugs,Sex,Self-Empowerment,Success,Hope,Celebration,Coming_Of_Age,Loneliness,Struggle,Love,Friendship,Traveling,SONG_ID
0,Vogue,Madonna,1990,Sunny,0.0,0.0,4.0,0.0,0.0,9.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7j5TIXPi0cCbSSqItmbyZy
1,Black or White,Michael Jackson,1991,Sunny,0.0,0.0,0.0,0.0,0.0,4.0,0.0,1.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,7EsjkelQuoUlJXEw7SeVV4
2,C.R.E.A.M.,Wu-Tang Clan,1993,Sunny,5.0,0.0,0.0,7.0,0.0,3.0,5.0,3.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,119c93MHjrDLJTApCVGpvx
3,Wonderwall,Oasis,1995,Sunny,0.0,1.0,0.0,0.0,0.0,6.0,0.0,10.0,0.0,0.0,0.0,0.0,10.0,2.0,0.0,7ygpwy2qP3NbrxVkHvUhXY
4,Don't Speak,No Doubt,1996,Sunny,0.0,10.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,7.0,5.0,10.0,2.0,0.0,6urCAbunOQI4bLhmGpX7iS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,Old Town Road,"Lil Nas X, Billy Ray Cyrus",2019,Dilraj,0.0,0.0,5.0,2.0,2.0,7.0,6.0,5.0,5.0,3.0,0.0,3.0,2.0,2.0,5.0,2YpeDb67231RjR0MgVLzsG
104,WAP,"Cardi B, Megan Thee Stallion",2020,Dilraj,1.0,0.0,7.0,0.0,10.0,8.0,6.0,2.0,5.0,0.0,0.0,2.0,2.0,2.0,0.0,4Oun2ylbjFKMPTiaSbbCih
105,Anti-Hero,Taylor Swift,2022,Dilraj,0.0,4.0,0.0,0.0,0.0,3.0,0.0,2.0,0.0,4.0,7.0,6.0,3.0,0.0,0.0,0V3wPSX9ygBnCm8psDIegu
106,Not Like Us,Kendrick Lamar,2024,Dilraj,7.0,2.0,4.0,0.0,2.0,8.0,5.0,2.0,2.0,2.0,0.0,5.0,0.0,2.0,0.0,6AI3ezQ4o3HUoP6Dhudph3
107,Ordinary,Alex Warren,2025,Dilraj,0.0,8.0,0.0,0.0,0.0,3.0,0.0,4.0,0.0,5.0,7.0,7.0,5.0,2.0,0.0,2RkZ5LkEzeHGRsmDqKwmaJ

In [57]:
final_CBM_input_data = pd.DataFrame()
final_CBM_input_data['SONG_TITLE'] = feature_data['Song Title']
final_CBM_input_data['ARTIST_NAME'] = feature_data['Artist']
final_CBM_input_data['SONG_ID'] = feature_data['SONG_ID']
feature_data = feature_data.drop(['Song Title','Artist','Release_Year', 'Reviewer','SONG_ID'], axis=1)
final_data = final_data.drop(['SONG_ID', 'Clean_Lyrics'], axis=1)
final_CBM_input_data = pd.concat([final_CBM_input_data, final_data], axis=1)
final_CBM_input_data

,SONG_TITLE,ARTIST_NAME,SONG_ID,Word_Count,Unique_Word_Count,Repetition_Score,Average_Line_Length,Vocabulary_Diversity,Title_Repetition,Explicit_Word_Count,Sentiment_Score,Positive_Score,Negative_Score,Emotional_Intensity,BERT_Embedding_0,BERT_Embedding_1,BERT_Embedding_2,BERT_Embedding_3,BERT_Embedding_4,BERT_Embedding_5,BERT_Embedding_6,BERT_Embedding_7,BERT_Embedding_8,BERT_Embedding_9,BERT_Embedding_10,BERT_Embedding_11,BERT_Embedding_12,BERT_Embedding_13,BERT_Embedding_14,BERT_Embedding_15,BERT_Embedding_16,BERT_Embedding_17,BERT_Embedding_18,BERT_Embedding_19,BERT_Embedding_20,BERT_Embedding_21,BERT_Embedding_22,BERT_Embedding_23,BERT_Embedding_24,BERT_Embedding_25,BERT_Embedding_26,BERT_Embedding_27,BERT_Embedding_28,BERT_Embedding_29,BERT_Embedding_30,BERT_Embedding_31,BERT_Embedding_32,BERT_Embedding_33,BERT_Embedding_34,BERT_Embedding_35,BERT_Embedding_36,BERT_Embedding_37,BERT_Embedding_38,BERT_Embedding_39,BERT_Embedding_40,BERT_Embedding_41,BERT_Embedding_42,BERT_Embedding_43,BERT_Embedding_44,BERT_Embedding_45,BERT_Embedding_46,BERT_Embedding_47,BERT_Embedding_48,BERT_Embedding_49,BERT_Embedding_50,BERT_Embedding_51,BERT_Embedding_52,BERT_Embedding_53,BERT_Embedding_54,BERT_Embedding_55,BERT_Embedding_56,BERT_Embedding_57,BERT_Embedding_58,BERT_Embedding_59,BERT_Embedding_60,BERT_Embedding_61,BERT_Embedding_62,BERT_Embedding_63,BERT_Embedding_64,BERT_Embedding_65,BERT_Embedding_66,BERT_Embedding_67,BERT_Embedding_68,BERT_Embedding_69,BERT_Embedding_70,BERT_Embedding_71,BERT_Embedding_72,BERT_Embedding_73,BERT_Embedding_74,BERT_Embedding_75,BERT_Embedding_76,BERT_Embedding_77,BERT_Embedding_78,BERT_Embedding_79,BERT_Embedding_80,BERT_Embedding_81,BERT_Embedding_82,BERT_Embedding_83,BERT_Embedding_84,BERT_Embedding_85,BERT_Embedding_86,BERT_Embedding_87,BERT_Embedding_88,BERT_Embedding_89,BERT_Embedding_90,BERT_Embedding_91,BERT_Embedding_92,BERT_Embedding_93,BERT_Embedding_94,BERT_Embedding_95,BERT_Embedding_96,BERT_Embedding_97,BERT_Embedding_98,BERT_Embedding_99,BERT_Embedding_100,BERT_Embedding_101,BERT_Embedding_102,BERT_Embedding_103,BERT_Embedding_104,BERT_Embedding_105,BERT_Embedding_106,BERT_Embedding_107,BERT_Embedding_108,BERT_Embedding_109,BERT_Embedding_110,BERT_Embedding_111,BERT_Embedding_112,BERT_Embedding_113,BERT_Embedding_114,BERT_Embedding_115,BERT_Embedding_116,BERT_Embedding_117,BERT_Embedding_118,BERT_Embedding_119,BERT_Embedding_120,BERT_Embedding_121,BERT_Embedding_122,BERT_Embedding_123,BERT_Embedding_124,BERT_Embedding_125,BERT_Embedding_126,BERT_Embedding_127,BERT_Embedding_128,BERT_Embedding_129,BERT_Embedding_130,BERT_Embedding_131,BERT_Embedding_132,BERT_Embedding_133,BERT_Embedding_134,BERT_Embedding_135,BERT_Embedding_136,BERT_Embedding_137,BERT_Embedding_138,BERT_Embedding_139,BERT_Embedding_140,BERT_Embedding_141,BERT_Embedding_142,BERT_Embedding_143,BERT_Embedding_144,BERT_Embedding_145,BERT_Embedding_146,BERT_Embedding_147,BERT_Embedding_148,BERT_Embedding_149,BERT_Embedding_150,BERT_Embedding_151,BERT_Embedding_152,BERT_Embedding_153,BERT_Embedding_154,BERT_Embedding_155,BERT_Embedding_156,BERT_Embedding_157,BERT_Embedding_158,BERT_Embedding_159,BERT_Embedding_160,BERT_Embedding_161,BERT_Embedding_162,BERT_Embedding_163,BERT_Embedding_164,BERT_Embedding_165,BERT_Embedding_166,BERT_Embedding_167,BERT_Embedding_168,BERT_Embedding_169,BERT_Embedding_170,BERT_Embedding_171,BERT_Embedding_172,BERT_Embedding_173,BERT_Embedding_174,BERT_Embedding_175,BERT_Embedding_176,BERT_Embedding_177,BERT_Embedding_178,BERT_Embedding_179,BERT_Embedding_180,BERT_Embedding_181,BERT_Embedding_182,BERT_Embedding_183,BERT_Embedding_184,BERT_Embedding_185,BERT_Embedding_186,BERT_Embedding_187,BERT_Embedding_188,BERT_Embedding_189,BERT_Embedding_190,BERT_Embedding_191,BERT_Embedding_192,BERT_Embedding_193,BERT_Embedding_194,BERT_Embedding_195,BERT_Embedding_196,BERT_Embedding_197,BERT_Embedding_198,BERT_Embedding_199,BERT_Embedding_200,BERT_Embedding_201,BERT_Embedding_202,BERT_Embedding_203,BERT_Embedding_204,BERT_Embedding_205,BERT_Embedding_206,BERT_Embedding_207,BERT_Embedding_208,BERT_Embedding_209,BERT_Embedding_210,BERT_Embedding_211,BERT_Embedding_212,BERT_Embedding_213,BERT_Embedding_214,BERT_Embedding_215,BERT_Embedding_216,BERT_Embedding_217,BERT_Embedding_218,BERT_Embedding_219,BERT_Embedding_220,BERT_Embedding_221,BERT_Embedding_222,BERT_Embedding_223,BERT_Embedding_224,BERT_Embedding_225,BERT_Embedding_226,BERT_Embedding_227,BERT_Embedding_228,BERT_Embedding_229,BERT_Embedding_230,BERT_Embedding_231,BERT_Embedding_232,BERT_Embedding_233,BERT_Embedding_234,BERT_Embedding_235,BERT_Embedding_236,BERT_Embedding_237,BERT_Embedding_238,BERT_Embedding_239,BERT_Embedding_240,BERT_Embedding_241,BERT_Embedding_242,BERT_Embedding_243,BERT_Embedding_244,BERT_Embedding_245,BERT_Embedding_246,BERT_Embedding_247,BERT_Embedding_248,BERT_Embedding_249,BERT_Embedding_250,BERT_Embedding_251,BERT_Embedding_252,BERT_Embedding_253,BERT_Embedding_254,BERT_Embedding_255,BERT_Embedding_256,BERT_Embedding_257,BERT_Embedding_258,BERT_Embedding_259,BERT_Embedding_260,BERT_Embedding_261,BERT_Embedding_262,BERT_Embedding_263,BERT_Embedding_264,BERT_Embedding_265,BERT_Embedding_266,BERT_Embedding_267,BERT_Embedding_268,BERT_Embedding_269,BERT_Embedding_270,BERT_Embedding_271,BERT_Embedding_272,BERT_Embedding_273,BERT_Embedding_274,BERT_Embedding_275,BERT_Embedding_276,BERT_Embedding_277,BERT_Embedding_278,BERT_Embedding_279,BERT_Embedding_280,BERT_Embedding_281,BERT_Embedding_282,BERT_Embedding_283,BERT_Embedding_284,BERT_Embedding_285,BERT_Embedding_286,BERT_Embedding_287,BERT_Embedding_288,BERT_Embedding_289,BERT_Embedding_290,BERT_Embedding_291,BERT_Embedding_292,BERT_Embedding_293,BERT_Embedding_294,BERT_Embedding_295,BERT_Embedding_296,BERT_Embedding_297,BERT_Embedding_298,BERT_Embedding_299,BERT_Embedding_300,BERT_Embedding_301,BERT_Embedding_302,BERT_Embedding_303,BERT_Embedding_304,BERT_Embedding_305,BERT_Embedding_306,BERT_Embedding_307,BERT_Embedding_308,BERT_Embedding_309,BERT_Embedding_310,BERT_Embedding_311,BERT_Embedding_312,BERT_Embedding_313,BERT_Embedding_314,BERT_Embedding_315,BERT_Embedding_316,BERT_Embedding_317,BERT_Embedding_318,BERT_Embedding_319,BERT_Embedding_320,BERT_Embedding_321,BERT_Embedding_322,BERT_Embedding_323,BERT_Embedding_324,BERT_Embedding_325,BERT_Embedding_326,BERT_Embedding_327,BERT_Embedding_328,BERT_Embedding_329,BERT_Embedding_330,BERT_Embedding_331,BERT_Embedding_332,BERT_Embedding_333,BERT_Embedding_334,BERT_Embedding_335,BERT_Embedding_336,BERT_Embedding_337,BERT_Embedding_338,BERT_Embedding_339,BERT_Embedding_340,BERT_Embedding_341,BERT_Embedding_342,BERT_Embedding_343,BERT_Embedding_344,BERT_Embedding_345,BERT_Embedding_346,BERT_Embedding_347,BERT_Embedding_348,BERT_Embedding_349,BERT_Embedding_350,BERT_Embedding_351,BERT_Embedding_352,BERT_Embedding_353,BERT_Embedding_354,BERT_Embedding_355,BERT_Embedding_356,BERT_Embedding_357,BERT_Embedding_358,BERT_Embedding_359,BERT_Embedding_360,BERT_Embedding_361,BERT_Embedding_362,BERT_Embedding_363,BERT_Embedding_364,BERT_Embedding_365,BERT_Embedding_366,BERT_Embedding_367,BERT_Embedding_368,BERT_Embedding_369,BERT_Embedding_370,BERT_Embedding_371,BERT_Embedding_372,BERT_Embedding_373,BERT_Embedding_374,BERT_Embedding_375,BERT_Embedding_376,BERT_Embedding_377,BERT_Embedding_378,BERT_Embedding_379,BERT_Embedding_380,BERT_Embedding_381,BERT_Embedding_382,BERT_Embedding_383
0,Vogue,Madonna,7j5TIXPi0cCbSSqItmbyZy,455,185,0.5934,5.9091,0.4066,34,0,0.9753,0.072,0.026,0.9753,0.032455,-0.020406,0.047048,0.004001,0.008487,0.009719,0.078765,-0.053172,-0.002942,-0.013091,-0.071279,0.019455,0.037108,-0.073128,0.040437,0.007649,0.051440,0.133707,-0.064686,0.092724,-0.015325,-0.039035,-0.078431,0.074520,-0.120340,0.061437,-0.025690,-0.063843,-0.044168,-0.033287,0.003789,0.077287,-0.027463,0.047424,-0.005885,0.081505,-0.067823,0.022822,-0.000809,0.090300,-0.009845,-0.030896,-0.013245,0.018173,0.061038,-0.052164,0.049487,0.009944,0.016456,0.008449,-0.091071,-0.042638,-0.037861,0.076814,0.022306,0.030891,0.041414,0.006084,0.025041,0.031125,-0.005604,-0.081221,-0.025031,0.028449,-0.002614,-0.034486,0.068054,0.056171,-0.034595,0.058267,0.023375,-0.117891,0.003391,0.065915,0.057882,0.092576,0.010887,-0.085392,-0.043355,-0.005817,0.015949,-0.008401,-0.035409,-0.061885,-0.063872,0.012390,-0.008102,0.034025,0.055166,-0.061142,-0.121393,0.041138,-0.105965,-0.089579,0.076957,-0.051344,-0.011547,-0.049339,-0.014422,0.037912,0.075117,-0.000107,0.052137,0.018820,-0.010957,-0.102126,0.087031,0.075581,0.014546,0.004803,-0.019055,-0.017605,0.019897,-0.013003,0.066464,-0.027534,0.013873,0.000055,0.044647,0.076714,-0.025768,-0.032804,-0.038597,-0.035812,-0.184865,0.008755,0.041734,-1.596165e-33,0.031315,0.041095,0.083099,0.088208,0.033834,-0.040240,-0.053107,-0.001964,-0.033040,0.086553,0.077468,-0.025645,-0.025536,0.083302,0.051197,-0.021958,-0.060891,-0.071541,0.052171,0.054887,0.018884,0.000913,-0.027546,-0.048034,-0.023387,0.047801,0.004269,-0.048233,-0.130753,-0.016313,0.033840,0.078249,0.042280,0.012024,-0.047288,-0.051203,-0.000989,0.023222,0.042546,-0.023236,-0.056710,0.017391,0.019378,0.002825,0.023471,0.101532,-0.013757,0.015938,0.043624,0.052646,0.052153,-0.049725,0.003291,-0.011615,-0.014069,-0.034340,-0.063538,-0.004348,0.077925,0.015198,0.027892,-0.035320,-0.037950,0.011477,0.057404,0.025543,-0.018115,-0.080954,0.053528,0.044077,-0.088820,-0.029560,-0.026807,0.045177,0.044155,-0.019539,-0.030136,-0.095866,-0.035175,0.065632,-0.023688,0.063422,-0.038833,0.084057,0.067575,-0.017991,0.033695,-0.013001,-0.034643,0.012438,-0.122378,0.064797,0.040184,-0.072434,-0.033459,6.991164e-34,0.119993,0.053709,0.058824,0.106079,0.094937,-0.003747,-0.030255,-0.015294,0.033511,0.033149,-0.026710,-0.076292,-0.029901,-0.060213,0.054843,-0.004996,-0.008451,0.028729,-0.071572,0.070094,-0.056793,0.033849,-0.031708,0.001521,-0.136645,-0.001287,0.029200,0.108253,0.033379,0.002297,0.007357,-0.003578,0.021689,-0.002958,-0.045004,0.055214,0.003491,-0.029228,-0.108438,0.020073,-0.086846,-0.053673,-0.020040,0.003990,0.001854,-0.078725,-0.028377,0.094136,-0.021642,0.030651,0.047013,-0.015046,-0.010781,0.009470,0.019455,-0.050176,0.038069,-0.046768,0.005775,0.020031,0.014121,0.048385,-0.057133,-0.022932,-0.033856,-0.006737,-0.022277,-0.019067,-0.058953,0.084408,-0.048655,0.004173,-0.021381,-0.001301,-0.080785,-0.041075,0.040742,-0.023276,-0.036696,-0.005443,0.012842,-0.058568,-0.022582,-0.024226,0.083300,0.131421,-0.021194,0.054174,-0.023625,-0.027411,-0.024811,0.031176,-0.033703,0.006982,-0.029947,-5.502888e-08,-0.035554,-0.018047,0.012605,0.007770,-0.045484,0.045097,0.019847,-0.050419,0.081992,-0.020658,0.032286,0.001018,0.053660,0.069895,-0.023172,-0.052519,-0.018580,0.042654,-0.047563,-0.001906,-0.000603,-0.022962,-0.001281,-0.094432,0.009686,-0.024482,0.043419,-0.014519,-0.057434,0.028747,0.012730,0.005823,0.021476,-0.013217,-0.074273,-0.027148,0.107083,-0.034320,-0.018001,-0.044997,-0.024483,0.045560,0.078554,-0.010164,-0.132855,-0.073192,0.092294,0.015037,-0.004141,0.021168,0.001270,-0.071914,0.012204,0.001284,0.020541,0.003309,-0.078053,0.120999,0.010399,0.037722,-0.001642,-0.026586,-0.028940,-0.081022
1,Black or White,Michael Jackson,7EsjkelQuoUlJXEw7SeVV4,141,56,0.6028,3.8108,0.3972,1,0,-0.9701,0.059,0.187,0.9701,0.011486,0.055678,0.075591,0.032436,0.043046,0.006275,0.029578,-0.070303,0.090080,-0.020128,-0.017440,-0.008217,0.032229,-0.025745,0.028203,0.073453,0.040940,0.009700,-0.128235,0.074903,-0.000771,0.160453,0.011514,-0.033375,-0.100990,0.034931,-0.054715,0.021306,0.052188,-0.036338,0.028748,-0.023675,0.068130,0.072311,0.057593,-0.024928,-0.056556,0.024365,-0.015452,-0.064875,-0.010226,0.004540,-0.035841,-0.057581,0.002122,-0.022570,-0.053218,-0.050524,0.056586,-0.027143,-0.053845,-0.050441,-0.031229,0.062528,0.011583,-0.011309,0.020230,0.058545,-0.024287,0.020442,-0.071611,0.000862,0.041271,-0.003093,0.017047,0.022338,0.068055,0.025522,-0.030435,0.095181,-0.064940,0.078670,0.014507,0.048324,-0.056349,0.010231,-0.026945,-0.014658,0.030454,0.071041,-0.102274,-0.028114,-0.031926,-0.046099,-0.031997,0.017985,0.038666,-0.080619,0.041674,-0.034820,-0.030591,-0.051617,0.016717,0.015406,0.038768,-0.048808,-0.064022,-0.049230,-0.140271,0.016680,0.022267,-0.055569,0.015672,-0.031862,0.005947,-0.021256,-0.067529,-0.011341,-0.098719,0.017855,-0.035456,-0.056807,-0.007026,-0.063567,-0.019761,-0.050275,0.042233,-0.019927,0.046496,0.083888,-0.099346,-0.016996,-0.102280,0.122343,-0.083292,-0.103001,-0.014288,9.391342e-33,-0.030236,-0.014698,-0.049001,-0.037633,-0.014089,0.006251,-0.000482,-0.020301,-0.000851,-0.046103,-0.004613,0.030294,0.052291,0.005909,0.039801,-0.036535,0.060438,-0.006479,0.043777,0.034962,-0.067480,0.054476,0.010524,0.012490,-0.111320,-0.014005,0.033302,-0.000404,-0.015254,0.019825,-0.022761,-0.014916,0.055637,-0.042979,0.034041,0.011702,0.018476,0.048066,-0.060992,-0.006794,-0.091921,0.065692,0.007113,-0.024092,-0.000264,0.015957,-0.044684,0.056109,-0.042673,0.010507,0.021789,-0.013798,0.019426,0.072324,-0.049066,0.030382,-0.081330,0.001630,0.027570,0.010127,-0.006011,-0.096573,0.105082,-0.032955,0.039346,-0.028263,-0.032258,-0.022417,-0.054938,-0.009202,-0.070878,-0.000849,0.015189,0.036289,0.016895,-0.053277,0.079018,-0.020212,0.051497,0.051766,-0.007298,0.018302,0.011726,0.048903,0.073822,-0.165851,0.043359,-0.113607,-0.012555,0.054400,-0.028385,0.049033,0.044523,-0.124189,-0.090182,-9.512260e-33,0.088647,0.014434,0.026938,0.096548,0.012864,0.022211,-0.108879,-0.001992,0.038920,0.061945,0.022199,-0.055897,-0.030457,0.004811,0.007227,-0.021878,0.085267,-0.023046,0.069206,0.002620,-0.027565,0.114480,0.054738,-0.007065,0.051997,-0.013626,0.040532,0.009857,-0.018044,0.055344,0.001256,-0.008028,-0.107962,0.084266,-0.000120,-0.064939,-0.008950,0.111680,-0.007110,-0.081622,-0.072894,-0.037241,-0.101109,0.019739,-0.025506,-0.078501,0.021953,0.034734,0.000428,0.080253,0.059408,0.016013,0.059821,0.017186,-0.020471,-0.034730,0.037588,-0.066542,-0.059206,-0.064309,0.025524,0.024705,-0.091181,0.014575,0.035787,0.020838,0.011203,-0.076292,-0.077753,-0.075606,-0.019650,-0.037182,-0.024602,0.027518,-0.004343,0.073040,0.007569,-0.135937,-0.047444,-0.019299,0.024703,-0.019832,-0.006188,0.055710,-0.036011,-0.021093,-0.042780,0.057717,-0.043677,0.042057,0.066487,-0.033996,0.048882,0.021766,-0.007663,-5.020267e-08,-0.031440,-0.010205,-0.078843,-0.032171,-0.018418,0.020683,0.050208,-0.082802,-0.006502,0.027251,0.075664,0.044662,-0.034271,0.039922,-0.051561,0.026508,0.066552,-0.075951,-0.029366,-0.061914,-0.049594,0.026766,-0.007410,-0.043432,-0.000841,0.062702,0.005938,-0.015358,-0.060144,0.016761,0.092963,-0.039684,0.022272,0.011419,-0.029063,0.014182,-0.079627,0.022213,-0.026964,0.052969,-0.055489,0.069675,0.109019,0.015625,-0.020509,-0.002770,0.028077,0.003264,-0.010883,0.009590,-0.007325,0.059645,0.014087,-0.003961,0.031227,0.083545,0.111336,0.024155,-0.043967,0.036285,0.126693,0.008918,0.032970,-0.058457
2,C.R.E.A.M.,Wu-Tang Clan,119c93MHjrDLJTApCVGpvx,611,291,0.5237,6.9432,0.4763,0,2,-0.4058,0.099,0.096,0.4058,-0.017920,-0.086241,0.014640,-0.053646,0.002245,0.016595,0.097720,-0.000657,0.033837,-0.039879,-0.051686,0.001328,-0.004426,-0.069052,-0.012947,0.051166,0.106182,0.034545,-0.045132,-0.005664,-0.023144,-0.061191,-0.024245,-0.002859,-0.101556,0.127012,-0.013064,0.034172,-0.021204,-0.046726,0.022053,0.061661,-0.028114,-0.050369,0.039745,0.003046,-0.066820,0.044128,0.003521,-0.003863,0.116545,0.022383,0.006916,0.007439,-0.031531,0.007265,-0.058094,-0.112379,0.003274,-0.017719,-0.056203,-0.071373,0.093495,0.123981,0.017068,0.029442,0.004515,0.056165,0.036337,0.010392,-0.071753,0.018914,0.016088,-0.009328,0.025819,0.021147,0.041295,0.055982,-0.020992,0.044069,-0.049347,0.007492,0.018437,0.053076,0.001342,0.059259,-0.096408,-0.103990,-0.000042,0.013704,0.025261,-0.013888,-0.048117,-0.140350,-0.085618,-0.021572,0.027435,0.018309,0.057500,-0.027584,-0.086109,0.078736,0.008465,-0.047638,0.038825,-0.017437,-0.029569,-0.042829,-0.031186,0.046128,0.069672,0.015531,-0.030232,-0.058379,0.072637,-0.035036,0.014856,0.044105,-0.018689,0.057792,-0.038566,0.011480,0.018758,-0.026458,0.091200,-0.005113,0.016596,0.083705,-0.048866,-0.068223,0.009045,0.026311,-0.017271,0.073583,-0.002896,-0.063736,-0.043466,1.012474e-33,0.002597,0.035429,-0.052273,0.044362,0.176471,-0.046336,0.024464,0.024610,-0.015078,0.128970,0.016027,-0.045383,-0.022750,0.018093,0.026507,-0.026501,-0.062778,-0.066104,-0.059856,0.003340,-0.075413,-0.040468,0.001676,0.084877,-0.031949,0.057115,-0.015949,0.027386,0.076528,-0.005844,-0.042377,0.001471,-0.046613,-0.004415,-0.008213,0.011500,0.023495,0.023401,-0.100222,-0.025482,-0.052881,-0.017490,-0.041842,0.020891,-0.041566,0.049618,-0.049101,0.010928,-0.011531,-0.024508,-0.006756,-0.011801,-0.004187,0.011147,-0.009249,0.023391,0.011149,0.072754,-0.004109,-0.019918,0.007991,-0.058438,-0.061489,-0.035045,0.008651,0.045643,-0.036890,-0.020993,0.102283,-0.042418,0.012982,-0.007044,-0.046839,-0.017781,0.060386,-0.001810,-0.041465,-0.064650,-0.003836,-0.007742,-0.001790,0.007972,-0.067231,0.077210,-0.050628,-0.080453,0.036039,-0.004257,-0.019003,0.041884,-0.147805,-0.006154,0.085166,0.022090,-0.038786,5.361555e-35,0.096663,0.027482,0.023940,0.097885,0.130081,-0.029715,-0.008443,-0.029465,0.073480,-0.057372,-0.002125,-0.072550,-0.047793,0.020884,0.090259,-0.062591,-0.057752,0.120598,0.059889,0.095144,-0.054260,0.058768,-0.044323,0.060753,-0.012053,0.071484,0.053098,0.077138,0.048028,0.085839,0.002645,0.041035,-0.027310,-0.092008,-0.033877,0.053695,-0.001819,-0.056945,-0.147183,-0.050628,-0.016193,-0.048099,-0.056560,0.054563,-0.042525,0.031356,0.011355,0.054455,0.003691,0.092703,0.046037,-0.019353,-0.051784,0.051369,-0.028509,-0.045694,-0.007164,0.019941,-0.029418,-0.007408,0.015998,0.034212,-0.004100,-0.012715,0.042361,0.002064,0.019899,0.000960,0.066042,0.007866,0.017348,0.097081,-0.045790,-0.012355,-0.011734,-0.049529,-0.030616,-0.094142,0.041868,-0.056254,0.006418,0.043038,-0.047118,0.043179,0.032455,0.032522,0.003540,0.010461,-0.092233,-0.009524,0.097812,-0.010473,-0.045452,0.052411,-0.012110,-5.299156e-08,0.030767,0.051519,-0.059258,0.034144,0.104555,-0.018169,-0.031940,0.004140,-0.019747,-0.021741,0.083270,-0.002511,0.080802,0.090133,-0.017988,0.036041,-0.033757,0.039042,-0.056004,-0.038465,-0.050435,0.048118,0.037691,-0.077663,-0.013950,-0.033296,0.034903,0.048036,0.009611,0.043075,-0.004657,0.015421,-0.009871,0.002431,0.034920,-0.065050,-0.022652,-0.035385,0.022374,-0.011935,-0.028381,0.080881,0.004241,-0.007524,-0.074608,-0.112243,-0.019402,0.018035,0.007090,0.078047,-0.021099,-0.024169,-0.002411,-0.007737,0.112197,0.003849,-0.033860,0.086991,-0.081059,0.022062,-0.010722,0.047732,0.052936,-0.123840

In [58]:
final_CBM_input_data.to_csv('C:/Users/maxph/OneDrive/Desktop/DS3-CLARIFY/data/training_data/final_CBM_input_data.csv', index=False)