In [1]:
import pandas as pd
import os
import time
import requests
import spotipy
from dotenv import load_dotenv
from spotipy.oauth2 import SpotifyClientCredentials

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
load_dotenv()
client_id = os.getenv('SPOTIPY_CLIENT_ID')
client_secret = os.getenv('SPOTIPY_CLIENT_SECRET')
sp = spotipy.Spotify(auth_manager=SpotifyClientCredentials(
    client_id=client_id, 
    client_secret=client_secret
))

In [3]:
def music_data_reader(file):
    music_data = pd.read_csv(file)
    return music_data

In [4]:
music_data = music_data_reader('C:/Users/maxph/OneDrive/Desktop/CLARIFY/SongList.csv')
music_data

,Song,Artist,Release_Year
0,Vogue,Madonna,1990
1,Enjoy the Silence,Depeche Mode,1990
2,Ice Ice Baby,Vanilla Ice,1990
3,Black or White,Michael Jackson,1991
4,Smells Like Teen Spirit,Nirvana,1991
5,Losing My Religion,R.E.M.,1991
6,Baby Got Back,Sir Mix-a-Lot,1992
7,I Will Always Love You,Whitney Houston,1992
8,Creep,Radiohead,1992
9,C.R.E.A.M.,Wu-Tang Clan,1993
10,All That She Wants,Ace of Base,1993
11,What Is Love,Haddaway,1993
12,Black Hole Sun,Soundgarden,1994
13,All I Want for Christmas Is You,Mariah Carey,1994
14,Basket Case,Green Day,1994
15,Wonderwall,Oasis,1995
16,Gangsta's Paradise,"Coolio, L.V.",1995
17,Waterfalls,TLC,1995
18,Don't Speak,No Doubt,1996
19,Wannabe,Spice Girls,1996
20,California Love,"2Pac, Dr. Dre",1996
21,Barbie Girl,Aqua,1997
22,My Heart Will Go On,Céline Dion,1997
23,Bitter Sweet Symphony,The Verve,1997
24,The Boy Is Mine,"Brandy, Monica",1998
25,I Don't Want to Miss a Thing,Aerosmith,1998
26,...Baby One More Time,Britney Spears,1998
27,No Scrubs,TLC,1999
28,Smooth,"Santana, Rob Thomas",1999
29,I Want It That Way,Backstreet Boys,1999
30,Oops!... I Did It Again,Britney Spears,2000
31,Bye Bye Bye,*NSYNC,2000
32,Stan,"Eminem, Dido",2000
33,Fallin',Alicia Keys,2001
34,In the End,Linkin Park,2001
35,How You Remind Me,Nickelback,2001
36,Hot in Herre,Nelly,2002
37,Lose Yourself,Eminem,2002
38,Complicated,Avril Lavigne,2002
39,Hey Ya!,Outkast,2003
40,In da Club,50 Cent,2003
41,Crazy in Love,"Beyoncé, JAY-Z",2003
42,Toxic,Britney Spears,2004
43,Mr. Brightside,The Killers,2004
44,Yeah!,"Usher, Lil Jon, Ludacris",2004
45,We Belong Together,Mariah Carey,2005
46,Gold Digger,"Kanye West, Jamie Foxx",2005
47,Feel Good Inc.,Gorillaz,2005
48,Crazy,Gnarls Barkley,2006
49,Hips Don't Lie,"Shakira, Wyclef Jean",2006
50,SexyBack,Justin Timberlake,2006
51,Crank That (Soulja Boy),Soulja Boy,2007
52,Umbrella,"Rihanna, JAY-Z",2007
53,Stronger,Kanye West,2007
54,Single Ladies (Put a Ring on It),Beyoncé,2008
55,Poker Face,Lady Gaga,2008
56,Viva La Vida,Coldplay,2008
57,Bad Romance,Lady Gaga,2009
58,Tik Tok,Kesha,2009
59,I Gotta Feeling,Black Eyed Peas,2009
60,Rolling in the Deep,Adele,2010
61,Teenage Dream,Katy Perry,2010
62,Love the Way You Lie,"Eminem, Rihanna",2010
63,We Found Love,"Rihanna, Calvin Harris",2011
64,Somebody That I Used to Know,"Gotye, Kimbra",2011
65,Party Rock Anthem,LMFAO,2011
66,Thrift Shop,"Macklemore, Ryan Lewis",2012
67,Gangnam Style,PSY,2012
68,Call Me Maybe,Carly Rae Jepsen,2012
69,Royals,Lorde,2013
70,Wake Me Up,Avicii,2013
71,Get Lucky,"Daft Punk, Pharrell Williams",2013
72,Shake It Off,Taylor Swift,2014
73,Thinking Out Loud,Ed Sheeran,2014
74,Uptown Funk,"Mark Ronson, Bruno Mars",2014
75,Hello,Adele,2015
76,Hotline Bling,Drake,2015
77,See You Again,"Wiz Khalifa, Charlie Puth",2015
78,Work,"Rihanna, Drake",2016
79,Closer,"The Chainsmokers, Halsey",2016
80,Starboy,"The Weeknd, Daft Punk",2016
81,HUMBLE.,Kendrick Lamar,2017
82,Shape of You,Ed Sheeran,2017
83,Despacito,"Luis Fonsi, Daddy Yankee",2017
84,"thank u, next",Ariana Grande,2018
85,Shallow,"Lady Gaga, Bradley Cooper",2018
86,God's Plan,Drake,2018
87,bad guy,Billie Eilish,2019
88,Blinding Lights,The Weeknd,2019
89,Old Town Road,"Lil Nas X, Billy Ray Cyrus",2019
90,Watermelon Sugar,Harry Styles,2020
91,Levitating,Dua Lipa,2020
92,WAP,"Cardi B, Megan Thee Stallion",2020
93,MONTERO (Call Me By Your Name),Lil Nas X,2021
94,drivers license,Olivia Rodrigo,2021
95,STAY,"The Kid LAROI, Justin Bieber",2021
96,Kill Bill,SZA,2022
97,As It Was,Harry Styles,2022
98,Anti-Hero,Taylor Swift,2022
99,Paint The Town Red,Doja Cat,2023
100,vampire,Olivia Rodrigo,2023
101,Flowers,Miley Cyrus,2023
102,Espresso,Sabrina Carpenter,2024
103,A Bar Song (Tipsy),Shaboozey,2024
104,Not Like Us,Kendrick Lamar,2024
105,Die With A Smile,"Lady Gaga, Bruno Mars",2025
106,luther,"Kendrick Lamar, SZA",2025
107,Ordinary,Alex Warren,2025

In [5]:
def fetch_spotify_id(row):
    # Convert to string in case of missing data (NaN)
    song = str(row['Song']) 
    artist = str(row['Artist'])
    
    # Format the query specifically for the Spotify search engine
    query = f"track:{song} artist:{artist}"
    
    try:
        # Search for 1 track matching the query
        results = sp.search(q=query, type='track', limit=1)
        items = results['tracks']['items']
        
        # If the list is not empty, extract the ID
        if items:
            return items[0]['id']
        else:
            print(f"No match found for: {song} by {artist}")
            return None
            
    except Exception as e:
        print(f"API Error fetching {song}: {e}")
        return None

In [6]:
music_data['SONG_ID'] = music_data.apply(fetch_spotify_id, axis=1)
music_data

,Song,Artist,Release_Year,SONG_ID
0,Vogue,Madonna,1990,7j5TIXPi0cCbSSqItmbyZy
1,Enjoy the Silence,Depeche Mode,1990,0yp3TvJNlG50Q4tAHWNCRm
2,Ice Ice Baby,Vanilla Ice,1990,3XVozq1aeqsJwpXrEZrDJ9
3,Black or White,Michael Jackson,1991,7EsjkelQuoUlJXEw7SeVV4
4,Smells Like Teen Spirit,Nirvana,1991,5ghIJDpPoe3CfHMGu71E6T
5,Losing My Religion,R.E.M.,1991,31AOj9sFz2gM0O3hMARRBx
6,Baby Got Back,Sir Mix-a-Lot,1992,1SAkL1mYNJlaqnBQxVZrRl
7,I Will Always Love You,Whitney Houston,1992,4eHbdreAnSOrDDsFfc4Fpm
8,Creep,Radiohead,1992,70LcF31zb1H0PyJoS1Sx1r
9,C.R.E.A.M.,Wu-Tang Clan,1993,119c93MHjrDLJTApCVGpvx
10,All That She Wants,Ace of Base,1993,6kWJvPfC4DgUpRsXKNa9z9
11,What Is Love,Haddaway,1993,0OTO8ZF2YqFQVw9hnZylTd
12,Black Hole Sun,Soundgarden,1994,2EoOZnxNgtmZaD8uUmz2nD
13,All I Want for Christmas Is You,Mariah Carey,1994,0bYg9bo50gSsH3LtXe2SQn
14,Basket Case,Green Day,1994,6L89mwZXSOwYl76YXfX13s
15,Wonderwall,Oasis,1995,7ygpwy2qP3NbrxVkHvUhXY
16,Gangsta's Paradise,"Coolio, L.V.",1995,1DIXPcTDzTj8ZMHt3PDt8p
17,Waterfalls,TLC,1995,6qspW4YKycviDFjHBOaqUY
18,Don't Speak,No Doubt,1996,6urCAbunOQI4bLhmGpX7iS
19,Wannabe,Spice Girls,1996,1Je1IMUlBXcx1Fz0WE7oPT
20,California Love,"2Pac, Dr. Dre",1996,3ia3dJETSOllPsv3LJkE35
21,Barbie Girl,Aqua,1997,5ZrDlcxIDZyjOzHdYW1ydr
22,My Heart Will Go On,Céline Dion,1997,33LC84JgLvK2KuW43MfaNq
23,Bitter Sweet Symphony,The Verve,1997,57iDDD9N9tTWe75x6qhStw
24,The Boy Is Mine,"Brandy, Monica",1998,6sHsXIJoEN5JpdkGMQDJxt
25,I Don't Want to Miss a Thing,Aerosmith,1998,5qlJg0Wbj3sslxfwiaRNpq
26,...Baby One More Time,Britney Spears,1998,3MjUtNVVq3C8Fn0MP3zhXa
27,No Scrubs,TLC,1999,1KGi9sZVMeszgZOWivFpxs
28,Smooth,"Santana, Rob Thomas",1999,2pX4FpOgwItRVPPUFdRcxA
29,I Want It That Way,Backstreet Boys,1999,47BBI51FKFwOMlIiX6m8ya
30,Oops!... I Did It Again,Britney Spears,2000,6naxalmIoLFWR0siv8dnQQ
31,Bye Bye Bye,*NSYNC,2000,62bOmKYxYg7dhrC6gH9vFn
32,Stan,"Eminem, Dido",2000,3UmaczJpikHgJFyBTAJVoz
33,Fallin',Alicia Keys,2001,0KQx6HOpJueiSkztcS0r7D
34,In the End,Linkin Park,2001,60a0Rd6pjrkxjPbaKzXjfq
35,How You Remind Me,Nickelback,2001,0gmbgwZ8iqyMPmXefof8Yf
36,Hot in Herre,Nelly,2002,04KTF78FFg8sOHC1BADqbY
37,Lose Yourself,Eminem,2002,5Z01UMMf7V1o0MzF86s6WJ
38,Complicated,Avril Lavigne,2002,5xEM5hIgJ1jjgcEBfpkt2F
39,Hey Ya!,Outkast,2003,2PpruBYCo4H7WOBJ7Q2EwM
40,In da Club,50 Cent,2003,4RY96Asd9IefaL3X4LOLZ8
41,Crazy in Love,"Beyoncé, JAY-Z",2003,5IVuqXILoxVWvWEPm82Jxr
42,Toxic,Britney Spears,2004,6I9VzXrHxO9rA9A5euc8Ak
43,Mr. Brightside,The Killers,2004,003vvx7Niy0yvhvHt4a68B
44,Yeah!,"Usher, Lil Jon, Ludacris",2004,5rb9QrpfcKFHM1EUbSIurX
45,We Belong Together,Mariah Carey,2005,3LmvfNUQtglbTrydsdIqFU
46,Gold Digger,"Kanye West, Jamie Foxx",2005,1PS1QMdUqOal0ai3Gt7sDQ
47,Feel Good Inc.,Gorillaz,2005,0d28khcov6AiegSCpG5TuT
48,Crazy,Gnarls Barkley,2006,6o1l9I0faXJN2iqulHrdCQ
49,Hips Don't Lie,"Shakira, Wyclef Jean",2006,3d0WouFnFmr0K3kjeza3fF
50,SexyBack,Justin Timberlake,2006,0O45fw2L5vsWpdsOdXwNAR
51,Crank That (Soulja Boy),Soulja Boy,2007,66TRwr5uJwPt15mfFkzhbi
52,Umbrella,"Rihanna, JAY-Z",2007,2yPoXCs7BSIUrucMdK5PzV
53,Stronger,Kanye West,2007,0j2T0R9dR9qdJYsB7ciXhf
54,Single Ladies (Put a Ring on It),Beyoncé,2008,2ZBNclC5wm4GtiWaeh0DMx
55,Poker Face,Lady Gaga,2008,5R8dQOPq8haW94K7mgERlO
56,Viva La Vida,Coldplay,2008,1mea3bSkSGXuIRvnydlB5b
57,Bad Romance,Lady Gaga,2009,0SiywuOBRcynK0uKGWdCnn
58,Tik Tok,Kesha,2009,0HPD5WQqrq7wPWR7P7Dw1i
59,I Gotta Feeling,Black Eyed Peas,2009,2H1047e0oMSj10dgp7p2VG
60,Rolling in the Deep,Adele,2010,1c8gk2PeTE04A1pIDH9YMk
61,Teenage Dream,Katy Perry,2010,5jzKL4BDMClWqRguW5qZvh
62,Love the Way You Lie,"Eminem, Rihanna",2010,15JINEqzVMv3SvJTAXAKED
63,We Found Love,"Rihanna, Calvin Harris",2011,6qn9YLKt13AGvpq9jfO8py
64,Somebody That I Used to Know,"Gotye, Kimbra",2011,4wCmqSrbyCgxEXROQE6vtV
65,Party Rock Anthem,LMFAO,2011,0IkKz2J93C94Ei4BvDop7P
66,Thrift Shop,"Macklemore, Ryan Lewis",2012,6CjtS2JZH9RkDz5UVInsa9
67,Gangnam Style,PSY,2012,03UrZgTINDqvnUMbbIMhql
68,Call Me Maybe,Carly Rae Jepsen,2012,3TGRqZ0a2l1LRblBkJoaDx
69,Royals,Lorde,2013,2dLLR6qlu5UJ5gk0dKz0h3
70,Wake Me Up,Avicii,2013,0nrRP2bk19rLc0orkWPQk2
71,Get Lucky,"Daft Punk, Pharrell Williams",2013,69kOkLUCkxIZYexIgSG8rq
72,Shake It Off,Taylor Swift,2014,5xTtaWoae3wi06K5WfVUUH
73,Thinking Out Loud,Ed Sheeran,2014,1Slwb6dOYkBlWal1PGtnNg
74,Uptown Funk,"Mark Ronson, Bruno Mars",2014,32OlwWuMpZ6b0aN2RZOeMS
75,Hello,Adele,2015,62PaSfnXSMyLshYJrlTuL3
76,Hotline Bling,Drake,2015,0wwPcA6wtMf6HUMpIRdeP7
77,See You Again,"Wiz Khalifa, Charlie Puth",2015,2JzZzZUQj3Qff7wapcbKjc
78,Work,"Rihanna, Drake",2016,72TFWvU3wUYdUuxejTTIzt
79,Closer,"The Chainsmokers, Halsey",2016,7BKLCZ1jbUBVqRi2FVlTVw
80,Starboy,"The Weeknd, Daft Punk",2016,7MXVkk9YMctZqd1Srtv4MB
81,HUMBLE.,Kendrick Lamar,2017,7KXjTSCq5nL1LoYtL7XAwS
82,Shape of You,Ed Sheeran,2017,7qiZfU4dY1lWllzX7mPBI3
83,Despacito,"Luis Fonsi, Daddy Yankee",2017,6habFhsOp2NvshLv26DqMb
84,"thank u, next",Ariana Grande,2018,3e9HZxeyfWwjeyPAMmWSSQ
85,Shallow,"Lady Gaga, Bradley Cooper",2018,2VxeLyX666F8uXCJ0dZF8B
86,God's Plan,Drake,2018,6DCZcSspjsKoFjzjrWoCdn
87,bad guy,Billie Eilish,2019,2Fxmhks0bxGSBdJ92vM42m
88,Blinding Lights,The Weeknd,2019,0VjIjW4GlUZAMYd2vXMi3b
89,Old Town Road,"Lil Nas X, Billy Ray Cyrus",2019,2YpeDb67231RjR0MgVLzsG
90,Watermelon Sugar,Harry Styles,2020,6UelLqGlWMcVH1E5c4H7lY
91,Levitating,Dua Lipa,2020,5nujrmhLynf4yMoMtj8AQF
92,WAP,"Cardi B, Megan Thee Stallion",2020,4Oun2ylbjFKMPTiaSbbCih
93,MONTERO (Call Me By Your Name),Lil Nas X,2021,1SC5rEoYDGUK4NfG82494W
94,drivers license,Olivia Rodrigo,2021,5wANPM4fQCJwkGd4rN57mH
95,STAY,"The Kid LAROI, Justin Bieber",2021,567e29TDzLwZwfDuEpGTwo
96,Kill Bill,SZA,2022,1Qrg8KqiBpW07V7PNxwwwL
97,As It Was,Harry Styles,2022,4Dvkj6JhhA12EX05fT7y2e
98,Anti-Hero,Taylor Swift,2022,0V3wPSX9ygBnCm8psDIegu
99,Paint The Town Red,Doja Cat,2023,2IGMVunIBsBLtEQyoI1Mu7
100,vampire,Olivia Rodrigo,2023,1kuGVB7EU95pJObxwvfwKS
101,Flowers,Miley Cyrus,2023,7DSAEUvxU8FajXtRloy8M0
102,Espresso,Sabrina Carpenter,2024,2HRqTpkrJO5ggZyyK6NPWz
103,A Bar Song (Tipsy),Shaboozey,2024,5fZJQrFKWQLb7FpJXZ1g7K
104,Not Like Us,Kendrick Lamar,2024,6AI3ezQ4o3HUoP6Dhudph3
105,Die With A Smile,"Lady Gaga, Bruno Mars",2025,2plbrEY59IikOBgBGLjaoe
106,luther,"Kendrick Lamar, SZA",2025,2CGNAOSuO1MEFCbBRgUzjd
107,Ordinary,Alex Warren,2025,2RkZ5LkEzeHGRsmDqKwmaJ

In [7]:
def fetch_lyrics(row):
    # Use your original Song and Artist columns for the search
    song = str(row['Song'])
    artist = str(row['Artist'])
    
    # Skip if missing data
    if pd.isna(song) or pd.isna(artist):
        return pd.Series({'Plain_Lyrics': None, 'Synced_Lyrics': None})

    # The LRCLIB Search Endpoint
    url = "https://lrclib.net/api/search"
    
    # requests will automatically format these into the URL
    params = {
        "track_name": song,
        "artist_name": artist
    }
    
    # The API docs politely ask for a User-Agent, so we will provide a generic one
    headers = {
        "User-Agent": "DataAnalysisScript/1.0"
    }

    try:
        response = requests.get(url, params=params, headers=headers)
        
        if response.status_code == 200:
            data = response.json()
            
            # The search API returns a list of matches. 
            # If the list is not empty, we take the top match (index 0).
            if len(data) > 0:
                top_match = data[0]
                return pd.Series({
                    'Plain_Lyrics': top_match.get('plainLyrics'),
                    'Synced_Lyrics': top_match.get('syncedLyrics')
                })
            else:
                print(f"No lyrics found for: {song} by {artist}")
        else:
            print(f"API Error {response.status_code} for {song}: {response.text}")
            
    except Exception as e:
        print(f"Network error fetching lyrics for {song}: {e}")
        
    # Politeness delay (even without rate limits, it's good practice)
    time.sleep(0.5)
    
    # Return empty if it fails
    return pd.Series({'Plain_Lyrics': None, 'Synced_Lyrics': None})

In [9]:
print("Searching LRCLIB for lyrics...")
lyrics_features = music_data.apply(fetch_lyrics, axis=1)
music_data = pd.concat([music_data, lyrics_features], axis=1)
music_data

Searching LRCLIB for lyrics...
Network error fetching lyrics for Watermelon Sugar: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

KeyboardInterrupt:

In [ ]:
music_data.to_csv('C:/Users/maxph/OneDrive/Desktop/CLARIFY/DS3-CLARIFY/TrainingData/lyrics_features.csv', index=False)