In [1]:
!pip install python-dotenv spotipy pandas

Requirement already satisfied: python-dotenv in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.2.2)
Requirement already satisfied: spotipy in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.26.0)
Requirement already satisfied: pandas in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.3.3)
Requirement already satisfied: redis>=3.5.3 in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (from spotipy) (7.4.0)
Requirement already satisfied: requests>=2.25.0 in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (from spotipy) (2.32.5)
Requirement already satisfied: urllib3>=1.26.0 in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (from spotipy) (2.6.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests>=2.25.0->spotipy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests>=2.25.0->spotipy) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests>=2.25.0->spotipy) (2026.1.4)

In [2]:
import pandas as pd
import numpy as np
import spotipy
import os
from dotenv import load_dotenv
from spotipy.oauth2 import SpotifyClientCredentials
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

load_dotenv()

client_id = os.getenv('SPOTIPY_CLIENT_ID')
client_secret = os.getenv('SPOTIPY_CLIENT_SECRET')

sp = spotipy.Spotify(auth_manager=SpotifyClientCredentials(
    client_id=client_id, 
    client_secret=client_secret
))

music_data = pd.read_csv('C:/Users/maxph/OneDrive/Desktop/CLARIFY/RevisedMusicData.csv')
music_data

,Song,Artist,Release Year,Tone,Lyrical Themes,Era Themes,Nostalgia Score (1-5),Lyrics,Tempo,Key Signature,Vocal Production,Valence,Danceable,Energy,Speechiness,Instrumentalness,Loudness,Energy.1,Popularity,Acousticness
0,Fantasy,Mariah Carey,1995,Romantic / Passionate,Love,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,One More Time,Daft Punk,2000,"Upbeat Anthem, Party / Club",Escapism / Partying,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Yellow,Coldplay,2000,"Chill / Laid Back, Romantic / Passionate",Love,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Oops!...I Did It Again,Britney Spears,2000,Upbeat Anthem,Coming of Age,Early Digital Age,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,In the End,Linkin Park,2001,Aggessive / Angsty,"Heartbreak, Coming of Age",Teenage Angst,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Get Ur Freak On,Missy Elliott,2001,Party / Club,"Escapism / Partying, Self-Empowerment",Cheap Thrills,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Fallin',Alicia Keys,2001,Romantic / Passionate,Love,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Clocks,Coldplay,2002,Melancholic / Moody,Coming of Age,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Lose Yourself,Eminem,2002,Chill / Laid Back,Coming of Age,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Complicated,Avril Lavigne,2002,"Upbeat Anthem, Aggessive / Angsty","Heartbreak, Coming of Age",Teenage Angst,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Cry Me a River,Justin Timberlake,2002,"Melancholic / Moody, Chill / Laid Back","Heartbreak, Coming of Age",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Hey Ya!,OutKast,2003,Upbeat Anthem,"Love, Escapism / Partying",Cheap Thrills,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,In Da Club,50 Cent,2003,Party / Club,Escapism / Partying,Bling Lifestyle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Crazy in Love,Beyoncé,2003,"Upbeat Anthem, Party / Club, Romantic / Passio...",Love,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Toxic,Britney Spears,2003,Romantic / Passionate,"Escapism / Partying, Love",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Yeah!,Usher,2004,Party / Club,"Escapism / Partying, Love",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Mr. Brightside,The Killers,2004,"Aggessive / Angsty, Melancholic / Moody","Coming of Age, Heartbreak",Teenage Angst,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,American Idiot,Green Day,2004,Aggessive / Angsty,Coming of Age,Socially Concious,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Since U Been Gone,Kelly Clarkson,2004,Melancholic / Moody,Heartbreak,Teenage Angst,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Feel Good Inc.,Gorillaz,2005,Chill / Laid Back,Coming of Age,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,"Sugar, We're Goin Down",Fall Out Boy,2005,"Aggessive / Angsty, Upbeat Anthem",Coming of Age,Teenage Angst,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Hips Don't Lie,Shakira,2006,"Romantic / Passionate, Upbeat Anthem",Coming of Age,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Crazy,Gnarls Barkley,2006,Chill / Laid Back,Love,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Low,Flo Rida,2007,Party / Club,Escapism / Partying,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Beautiful Girls,Sean Kingston,2007,Chill / Laid Back,Love,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Girlfriend,Avril Lavigne,2007,"Aggessive / Angsty, Upbeat Anthem",Coming of Age,Teenage Angst,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Umbrella,Rihanna,2007,"Romantic / Passionate, Chill / Laid Back",Self-Empowerment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Stronger,Kanye West,2007,Party / Club,Desires,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,I Kissed a Girl,Katy Perry,2008,"Aggessive / Angsty, Upbeat Anthem",Desires,Socially Concious,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Poker Face,Lady Gaga,2008,"Aggessive / Angsty, Party / Club",Coming of Age,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Kids,MGMT,2008,Upbeat Anthem,"Love, Coming of Age",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,You Belong With Me,Taylor Swift,2008,"Chill / Laid Back, Romantic / Passionate",Coming of Age,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Empire State of Mind,Jay-Z,2009,Chill / Laid Back,Escapism / Partying,Socially Concious,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,I Gotta Feeling,Black Eyed Peas,2009,"Upbeat Anthem, Party / Club",Heartbreak,Cheap Thrills,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Rolling in the Deep,Adele,2010,Melancholic / Moody,"Heartbreak, Self-Empowerment",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Runaway,Kanye West,2010,"Melancholic / Moody, Chill / Laid Back",Coming of Age,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Firework,Katy Perry,2010,Upbeat Anthem,"Love, Heartbreak",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Count on Me,Bruno Mars,2010,"Upbeat Anthem, Chill / Laid Back","Love, Coming of Age",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Last Friday Night (T.G.I.F.),Katy Perry,2010,"Upbeat Anthem, Party / Club","Desires, Coming of Age, Escapism / Partying","YOLO / Escapism, Cheap Thrills",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,California Gurls,Katy Perry,2010,Upbeat Anthem,Desires,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Call Me Maybe,Carly Rae Jepsen,2011,"Romantic / Passionate, Upbeat Anthem","Love, Coming of Age",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,We Found Love,Calvin Harris,2011,Party / Club,Heartbreak,YOLO / Escapism,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Somebody That I Used to Know,Gotye,2011,Melancholic / Moody,Love,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Pumped Up Kicks,Foster The People,2011,Chill / Laid Back,Coming of Age,Socially Concious,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,A Thousand Years,Christina Perri,2011,Romantic / Passionate,Love,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Die Young,Kesha,2012,"Party / Club, Upbeat Anthem",Escapism / Partying,YOLO / Escapism,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Beauty and a Beat,Justin Bieber,2012,Upbeat Anthem,Love,YOLO / Escapism,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Thinkin Bout You,Frank Ocean,2012,Chill / Laid Back,Love,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Thrift Shop,Macklemore,2012,Upbeat Anthem,Self-Empowerment,Cheap Thrills,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,Radioactive,Imagine Dragons,2012,"Aggessive / Angsty, Upbeat Anthem",Self-Empowerment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,Clarity,Zedd,2012,"Party / Club, Melancholic / Moody","Love, Heartbreak",NaN,NaN,NaN,NaN,NaN,Love,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,Payphone,Maroon 5,2012,Upbeat Anthem,Heartbreak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,Demons,Imagine Dragons,2012,Melancholic / Moody,Coming of Age,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,Cups,Anna Kendrick,2012,Upbeat Anthem,Coming of Age,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,Starships,Nicki Minaj,2012,Upbeat Anthem,Escapism / Partying,YOLO / Escapism,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,Get Lucky,Daft Punk,2013,Chill / Laid Back,Escapism / Partying,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,Wake Me Up,Avicii,2013,"Melancholic / Moody, Upbeat Anthem",Coming of Age,YOLO / Escapism,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,Take Me to Church,Hozier,2013,Melancholic / Moody,Coming of Age,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,Royals,Lorde,2013,Melancholic / Moody,Escapism / Partying,Teenage Angst,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,Turn Down for What,DJ Snake,2013,Party / Club,Escapism / Partying,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,Happy,Pharrell Williams,2013,Upbeat Anthem,Self-Empowerment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,Counting Stars,OneRepublic,2013,Upbeat Anthem,"Love, Coming of Age",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,Rude,MAGIC!,2013,Chill / Laid Back,Love,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,Timber,Pitbull,2013,"Upbeat Anthem, Party / Club",Escapism / Partying,YOLO / Escapism,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,Roar,Katy Perry,2013,Upbeat Anthem,Self-Empowerment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,Wrecking Ball,Miley Cyrus,2013,"Melancholic / Moody, Upbeat Anthem","Love, Heartbreak",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,Bang Bang,Jessie J,2014,Upbeat Anthem,Coming of Age,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,Uptown Funk,Mark Ronson,2014,Upbeat Anthem,Heartbreak,Bling Lifestyle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,Chandelier,Sia,2014,Melancholic / Moody,Self-Empowerment,YOLO / Escapism,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,Shake It Off,Taylor Swift,2014,Upbeat Anthem,Self-Empowerment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,Cheerleader,OMI,2014,"Romantic / Passionate, Chill / Laid Back","Love, Coming of Age",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,Shut Up and Dance,WALK THE MOON,2014,"Upbeat Anthem, Romantic / Passionate",Love,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,Maps,Maroon 5,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,Black Magic,Little Mix,2015,"Upbeat Anthem, Romantic / Passionate","Coming of Age, Love",Gossip / Drama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,Alright,Kendrick Lamar,2015,Chill / Laid Back,"Self-Empowerment, Coming of Age",Socially Concious,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,Hotline Bling,Drake,2015,Chill / Laid Back,Heartbreak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,Can't Feel My Face,The Weeknd,2015,Chill / Laid Back,Desires,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,Sorry,Justin Bieber,2015,Chill / Laid Back,"Love, Heartbreak",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,Stressed Out,Twenty One Pilots,2015,"Melancholic / Moody, Chill / Laid Back",Coming of Age,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,Stitches,Shawn Mendes,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,7 Years,Lukas Graham,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,Closer,The Chainsmokers,2016,"Upbeat Anthem, Melancholic / Moody","Heartbreak, Coming of Age","YOLO / Escapism, Cheap Thrills",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,Work,Fifth Harmony,2016,Upbeat Anthem,Love,Gossip / Drama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,Black Beatles,Rae Sremmurd,2016,"Melancholic / Moody, Chill / Laid Back","Heartbreak, Coming of Age",Teenage Angst,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,Bad and Boujee,Migos,2016,Chill / Laid Back,Desires,Bling Lifestyle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,That's What I Like,Bruno Mars,2017,"Upbeat Anthem, Romantic / Passionate",Love,YOLO / Escapism,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,Despacito,Luis Fonsi,2017,Upbeat Anthem,Desires,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,Shape of You,Ed Sheeran,2017,"Chill / Laid Back, Romantic / Passionate",Desires,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,Bodak Yellow,Cardi B,2017,"Chill / Laid Back, Aggessive / Angsty",Self-Empowerment,Bling Lifestyle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,Mask Off,Future,2017,Chill / Laid Back,Desires,Bling Lifestyle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,Something Just Like This,The Chainsmokers,2017,"Melancholic / Moody, Upbeat Anthem","Coming of Age, Desires",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,Perfect,Ed Sheeran,2017,Romantic / Passionate,Love,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
def fetch_spotify_id(row):
    # Convert to string in case of missing data (NaN)
    song = str(row['Song']) 
    artist = str(row['Artist'])
    
    # Format the query specifically for the Spotify search engine
    query = f"track:{song} artist:{artist}"
    
    try:
        # Search for 1 track matching the query
        results = sp.search(q=query, type='track', limit=1)
        items = results['tracks']['items']
        
        # If the list is not empty, extract the ID
        if items:
            return items[0]['id']
        else:
            print(f"No match found for: {song} by {artist}")
            return None
            
    except Exception as e:
        print(f"API Error fetching {song}: {e}")
        return None

In [7]:
music_data['SONG_ID'] = music_data.apply(fetch_spotify_id, axis=1)

In [18]:
music_data.columns = music_data.columns.str.strip()

# Now try your drop command again
music_data = music_data.drop(
    ['Tempo', 'Key Signature', 'Vocal Production', 'Valence', 'Danceable', 
     'Energy', 'Speechiness', 'Instrumentalness', 'Loudness', 'Energy.1', 
     'Popularity', 'Acousticness'], 
    axis=1, 
    errors='ignore'
)

music_data

,Song,Artist,Release Year,Tone,Lyrical Themes,Era Themes,Nostalgia Score (1-5),Lyrics,SONG_ID
0,Fantasy,Mariah Carey,1995,Romantic / Passionate,Love,NaN,NaN,NaN,6xkryXuiZU360Lngd4sx13
1,One More Time,Daft Punk,2000,"Upbeat Anthem, Party / Club",Escapism / Partying,NaN,NaN,NaN,0DiWol3AO6WpXZgp0goxAV
2,Yellow,Coldplay,2000,"Chill / Laid Back, Romantic / Passionate",Love,NaN,NaN,NaN,3AJwUDP919kvQ9QcozQPxg
3,Oops!...I Did It Again,Britney Spears,2000,Upbeat Anthem,Coming of Age,Early Digital Age,NaN,NaN,6naxalmIoLFWR0siv8dnQQ
4,In the End,Linkin Park,2001,Aggessive / Angsty,"Heartbreak, Coming of Age",Teenage Angst,NaN,NaN,60a0Rd6pjrkxjPbaKzXjfq
5,Get Ur Freak On,Missy Elliott,2001,Party / Club,"Escapism / Partying, Self-Empowerment",Cheap Thrills,NaN,NaN,6zsk6uF3MxfIeHPlubKBvR
6,Fallin',Alicia Keys,2001,Romantic / Passionate,Love,NaN,NaN,NaN,0KQx6HOpJueiSkztcS0r7D
7,Clocks,Coldplay,2002,Melancholic / Moody,Coming of Age,NaN,NaN,NaN,0BCPKOYdS2jbQ8iyB56Zns
8,Lose Yourself,Eminem,2002,Chill / Laid Back,Coming of Age,NaN,NaN,NaN,5Z01UMMf7V1o0MzF86s6WJ
9,Complicated,Avril Lavigne,2002,"Upbeat Anthem, Aggessive / Angsty","Heartbreak, Coming of Age",Teenage Angst,NaN,NaN,5xEM5hIgJ1jjgcEBfpkt2F
10,Cry Me a River,Justin Timberlake,2002,"Melancholic / Moody, Chill / Laid Back","Heartbreak, Coming of Age",NaN,NaN,NaN,7Lf7oSEVdzZqTA0kEDSlS5
11,Hey Ya!,OutKast,2003,Upbeat Anthem,"Love, Escapism / Partying",Cheap Thrills,NaN,NaN,2PpruBYCo4H7WOBJ7Q2EwM
12,In Da Club,50 Cent,2003,Party / Club,Escapism / Partying,Bling Lifestyle,NaN,NaN,4RY96Asd9IefaL3X4LOLZ8
13,Crazy in Love,Beyoncé,2003,"Upbeat Anthem, Party / Club, Romantic / Passio...",Love,NaN,NaN,NaN,5IVuqXILoxVWvWEPm82Jxr
14,Toxic,Britney Spears,2003,Romantic / Passionate,"Escapism / Partying, Love",NaN,NaN,NaN,6I9VzXrHxO9rA9A5euc8Ak
15,Yeah!,Usher,2004,Party / Club,"Escapism / Partying, Love",NaN,NaN,NaN,5rb9QrpfcKFHM1EUbSIurX
16,Mr. Brightside,The Killers,2004,"Aggessive / Angsty, Melancholic / Moody","Coming of Age, Heartbreak",Teenage Angst,NaN,NaN,003vvx7Niy0yvhvHt4a68B
17,American Idiot,Green Day,2004,Aggessive / Angsty,Coming of Age,Socially Concious,NaN,NaN,6nTiIhLmQ3FWhvrGafw2zj
18,Since U Been Gone,Kelly Clarkson,2004,Melancholic / Moody,Heartbreak,Teenage Angst,NaN,NaN,3xrn9i8zhNZsTtcoWgQEAd
19,Feel Good Inc.,Gorillaz,2005,Chill / Laid Back,Coming of Age,NaN,NaN,NaN,0d28khcov6AiegSCpG5TuT
20,"Sugar, We're Goin Down",Fall Out Boy,2005,"Aggessive / Angsty, Upbeat Anthem",Coming of Age,Teenage Angst,NaN,NaN,2TfSHkHiFO4gRztVIkggkE
21,Hips Don't Lie,Shakira,2006,"Romantic / Passionate, Upbeat Anthem",Coming of Age,NaN,NaN,NaN,3d0WouFnFmr0K3kjeza3fF
22,Crazy,Gnarls Barkley,2006,Chill / Laid Back,Love,NaN,NaN,NaN,6o1l9I0faXJN2iqulHrdCQ
23,Low,Flo Rida,2007,Party / Club,Escapism / Partying,NaN,NaN,NaN,0CAfXk7DXMnon4gLudAp7J
24,Beautiful Girls,Sean Kingston,2007,Chill / Laid Back,Love,NaN,NaN,NaN,1hGy2eLcmC8eKx7qr1tOqx
25,Girlfriend,Avril Lavigne,2007,"Aggessive / Angsty, Upbeat Anthem",Coming of Age,Teenage Angst,NaN,NaN,45hOioMDJktr86iKDHC8gr
26,Umbrella,Rihanna,2007,"Romantic / Passionate, Chill / Laid Back",Self-Empowerment,NaN,NaN,NaN,2yPoXCs7BSIUrucMdK5PzV
27,Stronger,Kanye West,2007,Party / Club,Desires,NaN,NaN,NaN,0j2T0R9dR9qdJYsB7ciXhf
28,I Kissed a Girl,Katy Perry,2008,"Aggessive / Angsty, Upbeat Anthem",Desires,Socially Concious,NaN,NaN,005lwxGU1tms6HGELIcUv9
29,Poker Face,Lady Gaga,2008,"Aggessive / Angsty, Party / Club",Coming of Age,NaN,NaN,NaN,5R8dQOPq8haW94K7mgERlO
30,Kids,MGMT,2008,Upbeat Anthem,"Love, Coming of Age",NaN,NaN,NaN,1jJci4qxiYcOHhQR247rEU
31,You Belong With Me,Taylor Swift,2008,"Chill / Laid Back, Romantic / Passionate",Coming of Age,NaN,NaN,NaN,3GCL1PydwsLodcpv0Ll1ch
32,Empire State of Mind,Jay-Z,2009,Chill / Laid Back,Escapism / Partying,Socially Concious,NaN,NaN,2igwFfvr1OAGX9SKDCPBwO
33,I Gotta Feeling,Black Eyed Peas,2009,"Upbeat Anthem, Party / Club",Heartbreak,Cheap Thrills,NaN,NaN,2H1047e0oMSj10dgp7p2VG
34,Rolling in the Deep,Adele,2010,Melancholic / Moody,"Heartbreak, Self-Empowerment",NaN,NaN,NaN,1c8gk2PeTE04A1pIDH9YMk
35,Runaway,Kanye West,2010,"Melancholic / Moody, Chill / Laid Back",Coming of Age,NaN,NaN,NaN,3DK6m7It6Pw857FcQftMds
36,Firework,Katy Perry,2010,Upbeat Anthem,"Love, Heartbreak",NaN,NaN,NaN,4r6eNCsrZnQWJzzvFh4nlg
37,Count on Me,Bruno Mars,2010,"Upbeat Anthem, Chill / Laid Back","Love, Coming of Age",NaN,NaN,NaN,7l1qvxWjxcKpB9PCtBuTbU
38,Last Friday Night (T.G.I.F.),Katy Perry,2010,"Upbeat Anthem, Party / Club","Desires, Coming of Age, Escapism / Partying","YOLO / Escapism, Cheap Thrills",NaN,NaN,3avYqdwHKEq8beXbeWCKqJ
39,California Gurls,Katy Perry,2010,Upbeat Anthem,Desires,NaN,NaN,NaN,6KOEK6SeCEZOQkLj5M1PxH
40,Call Me Maybe,Carly Rae Jepsen,2011,"Romantic / Passionate, Upbeat Anthem","Love, Coming of Age",NaN,NaN,NaN,3TGRqZ0a2l1LRblBkJoaDx
41,We Found Love,Calvin Harris,2011,Party / Club,Heartbreak,YOLO / Escapism,NaN,NaN,6qn9YLKt13AGvpq9jfO8py
42,Somebody That I Used to Know,Gotye,2011,Melancholic / Moody,Love,NaN,NaN,NaN,4wCmqSrbyCgxEXROQE6vtV
43,Pumped Up Kicks,Foster The People,2011,Chill / Laid Back,Coming of Age,Socially Concious,NaN,NaN,7w87IxuO7BDcJ3YUqCyMTT
44,A Thousand Years,Christina Perri,2011,Romantic / Passionate,Love,NaN,NaN,NaN,6lanRgr6wXibZr8KgzXxBl
45,Die Young,Kesha,2012,"Party / Club, Upbeat Anthem",Escapism / Partying,YOLO / Escapism,NaN,NaN,7EQGXaVSyEDsCWKmUcfpLk
46,Beauty and a Beat,Justin Bieber,2012,Upbeat Anthem,Love,YOLO / Escapism,NaN,NaN,6QFCMUUq1T2Vf5sFUXcuQ7
47,Thinkin Bout You,Frank Ocean,2012,Chill / Laid Back,Love,NaN,NaN,NaN,7DfFc7a6Rwfi3YQMRbDMau
48,Thrift Shop,Macklemore,2012,Upbeat Anthem,Self-Empowerment,Cheap Thrills,NaN,NaN,6CjtS2JZH9RkDz5UVInsa9
49,Radioactive,Imagine Dragons,2012,"Aggessive / Angsty, Upbeat Anthem",Self-Empowerment,NaN,NaN,NaN,4G8gkOterJn0Ywt6uhqbhp
50,Clarity,Zedd,2012,"Party / Club, Melancholic / Moody","Love, Heartbreak",NaN,NaN,NaN,60wwxj6Dd9NJlirf84wr2c
51,Payphone,Maroon 5,2012,Upbeat Anthem,Heartbreak,NaN,NaN,NaN,4P0osvTXoSYZZC2n8IFH3c
52,Demons,Imagine Dragons,2012,Melancholic / Moody,Coming of Age,NaN,NaN,NaN,3LlAyCYU26dvFZBDUIMb7a
53,Cups,Anna Kendrick,2012,Upbeat Anthem,Coming of Age,NaN,NaN,NaN,6mH3qVIeOsnQIAho5eWwhH
54,Starships,Nicki Minaj,2012,Upbeat Anthem,Escapism / Partying,YOLO / Escapism,NaN,NaN,1oHNvJVbFkexQc0BpQp7Y4
55,Get Lucky,Daft Punk,2013,Chill / Laid Back,Escapism / Partying,NaN,NaN,NaN,69kOkLUCkxIZYexIgSG8rq
56,Wake Me Up,Avicii,2013,"Melancholic / Moody, Upbeat Anthem",Coming of Age,YOLO / Escapism,NaN,NaN,0nrRP2bk19rLc0orkWPQk2
57,Take Me to Church,Hozier,2013,Melancholic / Moody,Coming of Age,NaN,NaN,NaN,1CS7Sd1u5tWkstBhpssyjP
58,Royals,Lorde,2013,Melancholic / Moody,Escapism / Partying,Teenage Angst,NaN,NaN,2dLLR6qlu5UJ5gk0dKz0h3
59,Turn Down for What,DJ Snake,2013,Party / Club,Escapism / Partying,NaN,NaN,NaN,67awxiNHNyjMXhVgsHuIrs
60,Happy,Pharrell Williams,2013,Upbeat Anthem,Self-Empowerment,NaN,NaN,NaN,60nZcImufyMA1MKQY3dcCH
61,Counting Stars,OneRepublic,2013,Upbeat Anthem,"Love, Coming of Age",NaN,NaN,NaN,2tpWsVSb9UEmDRxAl1zhX1
62,Rude,MAGIC!,2013,Chill / Laid Back,Love,NaN,NaN,NaN,6RtPijgfPKROxEzTHNRiDp
63,Timber,Pitbull,2013,"Upbeat Anthem, Party / Club",Escapism / Partying,YOLO / Escapism,NaN,NaN,3cHyrEgdyYRjgJKSOiOtcS
64,Roar,Katy Perry,2013,Upbeat Anthem,Self-Empowerment,NaN,NaN,NaN,27tNWlhdAryQY04Gb2ZhUI
65,Wrecking Ball,Miley Cyrus,2013,"Melancholic / Moody, Upbeat Anthem","Love, Heartbreak",NaN,NaN,NaN,2vwlzO0Qp8kfEtzTsCXfyE
66,Bang Bang,Jessie J,2014,Upbeat Anthem,Coming of Age,NaN,NaN,NaN,0puf9yIluy9W0vpMEUoAnN
67,Uptown Funk,Mark Ronson,2014,Upbeat Anthem,Heartbreak,Bling Lifestyle,NaN,NaN,32OlwWuMpZ6b0aN2RZOeMS
68,Chandelier,Sia,2014,Melancholic / Moody,Self-Empowerment,YOLO / Escapism,NaN,NaN,2s1sdSqGcKxpPr5lCl7jAV
69,Shake It Off,Taylor Swift,2014,Upbeat Anthem,Self-Empowerment,NaN,NaN,NaN,5xTtaWoae3wi06K5WfVUUH
70,Cheerleader,OMI,2014,"Romantic / Passionate, Chill / Laid Back","Love, Coming of Age",NaN,NaN,NaN,023OVLNzXhX0j7CxswUt6D
71,Shut Up and Dance,WALK THE MOON,2014,"Upbeat Anthem, Romantic / Passionate",Love,NaN,NaN,NaN,4kbj5MwxO1bq9wjT5g9HaA
72,Maps,Maroon 5,2014,NaN,NaN,NaN,NaN,NaN,4gbVRS8gloEluzf0GzDOFc
73,Black Magic,Little Mix,2015,"Upbeat Anthem, Romantic / Passionate","Coming of Age, Love",Gossip / Drama,NaN,NaN,6rmXhRIemCTPyMYZRDN7Qg
74,Alright,Kendrick Lamar,2015,Chill / Laid Back,"Self-Empowerment, Coming of Age",Socially Concious,NaN,NaN,3iVcZ5G6tvkXZkZKlMpIUs
75,Hotline Bling,Drake,2015,Chill / Laid Back,Heartbreak,NaN,NaN,NaN,0wwPcA6wtMf6HUMpIRdeP7
76,Can't Feel My Face,The Weeknd,2015,Chill / Laid Back,Desires,NaN,NaN,NaN,22VdIZQfgXJea34mQxlt81
77,Sorry,Justin Bieber,2015,Chill / Laid Back,"Love, Heartbreak",NaN,NaN,NaN,09CtPGIpYB4BrO8qb1RGsF
78,Stressed Out,Twenty One Pilots,2015,"Melancholic / Moody, Chill / Laid Back",Coming of Age,NaN,NaN,NaN,3CRDbSIZ4r5MsZ0YwxuEkn
79,Stitches,Shawn Mendes,2015,NaN,NaN,NaN,NaN,NaN,5jsw9uXEGuKyJzs0boZ1bT
80,7 Years,Lukas Graham,2015,NaN,NaN,NaN,NaN,NaN,5kqIPrATaCc2LqxVWzQGbk
81,Closer,The Chainsmokers,2016,"Upbeat Anthem, Melancholic / Moody","Heartbreak, Coming of Age","YOLO / Escapism, Cheap Thrills",NaN,NaN,7BKLCZ1jbUBVqRi2FVlTVw
82,Work,Fifth Harmony,2016,Upbeat Anthem,Love,Gossip / Drama,NaN,NaN,4tCtwWceOPWzenK2HAIJSb
83,Black Beatles,Rae Sremmurd,2016,"Melancholic / Moody, Chill / Laid Back","Heartbreak, Coming of Age",Teenage Angst,NaN,NaN,6fujklziTHa8uoM5OQSfIo
84,Bad and Boujee,Migos,2016,Chill / Laid Back,Desires,Bling Lifestyle,NaN,NaN,0M9ydKzuF3oZTfYYPfaGX1
85,That's What I Like,Bruno Mars,2017,"Upbeat Anthem, Romantic / Passionate",Love,YOLO / Escapism,NaN,NaN,0KKkJNfGyhkQ5aFogxQAPU
86,Despacito,Luis Fonsi,2017,Upbeat Anthem,Desires,NaN,NaN,NaN,6habFhsOp2NvshLv26DqMb
87,Shape of You,Ed Sheeran,2017,"Chill / Laid Back, Romantic / Passionate",Desires,NaN,NaN,NaN,7qiZfU4dY1lWllzX7mPBI3
88,Bodak Yellow,Cardi B,2017,"Chill / Laid Back, Aggessive / Angsty",Self-Empowerment,Bling Lifestyle,NaN,NaN,6KBYefIoo7KydImq1uUQlL
89,Mask Off,Future,2017,Chill / Laid Back,Desires,Bling Lifestyle,NaN,NaN,0VgkVdmE4gld66l8iyGjgx
90,Something Just Like This,The Chainsmokers,2017,"Melancholic / Moody, Upbeat Anthem","Coming of Age, Desires",NaN,NaN,NaN,6RUKPb4LETWmmr3iAEQktW
91,Perfect,Ed Sheeran,2017,Romantic / Passionate,Love,NaN,NaN,NaN,0tgVpDi06FyKpA1z0VMD4v

In [24]:
import time
import requests

# Ensure your RapidAPI key is loaded
load_dotenv()
RAPIDAPI_KEY = os.getenv('RAPIDAPI_KEY')

def fetch_all_soundnet_features(row):
    # Grab the Spotify ID we generated earlier
    spotify_id = row.get('SONG_ID')
    
    # Define the exact columns we expect to create
    feature_columns = [
        'SoundNet_ID', 'Track_Name', 'Album', 'Key', 'Mode', 'Camelot', 
        'Tempo', 'Duration', 'Popularity', 'Energy', 'Danceability', 
        'Happiness', 'Acousticness', 'Instrumentalness', 'Liveness', 
        'Speechiness', 'Loudness'
    ]
    
    # If there is no ID, return a row of empty values
    if pd.isna(spotify_id) or not spotify_id:
        return pd.Series({col: None for col in feature_columns})

    # The API endpoint
    url = f"https://track-analysis.p.rapidapi.com/pktx/spotify/{spotify_id}"
    
    headers = {
        "x-rapidapi-key": RAPIDAPI_KEY,
        "x-rapidapi-host": "track-analysis.p.rapidapi.com"
    }
    
    try:
        response = requests.get(url, headers=headers)
        
        if response.status_code == 200:
            data = response.json()
            
            # Rate limiting sleep (1 second between successful calls)
            time.sleep(1)
            
            # Map the JSON data directly into a pandas Series
            return pd.Series({
                'SoundNet_ID': data.get('id'),
                'Track_Name': data.get('name'),
                'Album': data.get('album'),
                'Key': data.get('key'),
                'Mode': data.get('mode'),
                'Camelot': data.get('camelot'),
                'Tempo': data.get('tempo'),
                'Duration': data.get('duration'),
                'Popularity': data.get('popularity'),
                'Energy': data.get('energy'),
                'Danceability': data.get('danceability'),
                'Happiness': data.get('happiness'),
                'Acousticness': data.get('acousticness'),
                'Instrumentalness': data.get('instrumentalness'),
                'Liveness': data.get('liveness'),
                'Speechiness': data.get('speechiness'),
                'Loudness': data.get('loudness')
            })
        else:
            print(f"API Error {response.status_code} for ID {spotify_id}: {response.text}")
            
    except Exception as e:
        print(f"Network error for ID {spotify_id}: {e}")
    
    # Fallback rate limiting in case of errors
    time.sleep(1) 
    
    # Return empty data if the API call failed
    return pd.Series({col: None for col in feature_columns})

In [26]:
print("Fetching comprehensive audio features from SoundNet...")
new_audio_features = music_data.apply(fetch_all_soundnet_features, axis=1)

# 5. Add the new columns to the dataframe
print("Merging new columns into the dataset...")
music_data = pd.concat([music_data, new_audio_features], axis=1)

music_data

Fetching comprehensive audio features from SoundNet...

KeyboardInterrupt: