In [1]:
!pip install python-dotenv spotipy pandas

Requirement already satisfied: python-dotenv in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.2.2)
Requirement already satisfied: spotipy in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.26.0)
Requirement already satisfied: pandas in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.3.3)
Requirement already satisfied: redis>=3.5.3 in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (from spotipy) (7.4.0)
Requirement already satisfied: requests>=2.25.0 in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (from spotipy) (2.32.5)
Requirement already satisfied: urllib3>=1.26.0 in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (from spotipy) (2.6.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests>=2.25.0->spotipy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests>=2.25.0->spotipy) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\maxph\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests>=2.25.0->spotipy) (2026.1.4)

In [1]:
import pandas as pd
import numpy as np
import spotipy
import os
from dotenv import load_dotenv
from spotipy.oauth2 import SpotifyClientCredentials
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

load_dotenv()

client_id = os.getenv('SPOTIPY_CLIENT_ID')
client_secret = os.getenv('SPOTIPY_CLIENT_SECRET')

sp = spotipy.Spotify(auth_manager=SpotifyClientCredentials(
    client_id=client_id, 
    client_secret=client_secret
))

music_data = pd.read_csv('C:/Users/maxph/OneDrive/Desktop/CLARIFY/ExpandedMusicData.csv')
music_data

,Song,Artist,Release_Year,Violence,Heartbreak,Partying,Drugs,Sex,Self-Empowerment,Success,Hope,Celebration,Coming_Of_Age,Loneliness,Struggle,Love,Friendship,Traveling
0,Vogue,Madonna,1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Enjoy the Silence,Depeche Mode,1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ice Ice Baby,Vanilla Ice,1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Smells Like Teen Spirit,Nirvana,1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Losing My Religion,R.E.M.,1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Black or White,Michael Jackson,1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,I Will Always Love You,Whitney Houston,1992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Creep,Radiohead,1992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Baby Got Back,Sir Mix-a-Lot,1992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,What Is Love,Haddaway,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,C.R.E.A.M.,Wu-Tang Clan,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,All That She Wants,Ace of Base,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Basket Case,Green Day,1994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Black Hole Sun,Soundgarden,1994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,All I Want for Christmas Is You,Mariah Carey,1994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Wonderwall,Oasis,1995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Gangsta's Paradise,"Coolio, L.V.",1995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Waterfalls,TLC,1995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Wannabe,Spice Girls,1996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,California Love,"2Pac, Dr. Dre",1996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Don't Speak,No Doubt,1996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,My Heart Will Go On,Céline Dion,1997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Bitter Sweet Symphony,The Verve,1997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Barbie Girl,Aqua,1997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,...Baby One More Time,Britney Spears,1998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,The Boy Is Mine,"Brandy, Monica",1998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,I Don't Want to Miss a Thing,Aerosmith,1998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,I Want It That Way,Backstreet Boys,1999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,No Scrubs,TLC,1999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Smooth,"Santana, Rob Thomas",1999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Oops!... I Did It Again,Britney Spears,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Bye Bye Bye,*NSYNC,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Stan,"Eminem, Dido",2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,In the End,Linkin Park,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,How You Remind Me,Nickelback,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Fallin',Alicia Keys,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Lose Yourself,Eminem,2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Complicated,Avril Lavigne,2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Hot in Herre,Nelly,2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Crazy in Love,"Beyoncé, JAY-Z",2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Hey Ya!,Outkast,2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,In da Club,50 Cent,2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Yeah!,"Usher, Lil Jon, Ludacris",2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Mr. Brightside,The Killers,2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,Toxic,Britney Spears,2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Gold Digger,"Kanye West, Jamie Foxx",2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,We Belong Together,Mariah Carey,2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Feel Good Inc.,Gorillaz,2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Hips Don't Lie,"Shakira, Wyclef Jean",2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,SexyBack,Justin Timberlake,2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,Crazy,Gnarls Barkley,2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,Umbrella,"Rihanna, JAY-Z",2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,Stronger,Kanye West,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,Crank That (Soulja Boy),Soulja Boy,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,Viva La Vida,Coldplay,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,Single Ladies (Put a Ring on It),Beyoncé,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,Poker Face,Lady Gaga,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,I Gotta Feeling,Black Eyed Peas,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,Bad Romance,Lady Gaga,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,Tik Tok,Kesha,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,Rolling in the Deep,Adele,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,Teenage Dream,Katy Perry,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,Love the Way You Lie,"Eminem, Rihanna",2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,Somebody That I Used to Know,"Gotye, Kimbra",2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,Party Rock Anthem,LMFAO,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,We Found Love,"Rihanna, Calvin Harris",2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,Gangnam Style,PSY,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,Call Me Maybe,Carly Rae Jepsen,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,Thrift Shop,"Macklemore, Ryan Lewis",2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,Get Lucky,"Daft Punk, Pharrell Williams",2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,Royals,Lorde,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,Wake Me Up,Avicii,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,Uptown Funk,"Mark Ronson, Bruno Mars",2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,Shake It Off,Taylor Swift,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,Thinking Out Loud,Ed Sheeran,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,Hello,Adele,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,Hotline Bling,Drake,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,See You Again,"Wiz Khalifa, Charlie Puth",2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,Closer,"The Chainsmokers, Halsey",2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,Starboy,"The Weeknd, Daft Punk",2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,Work,"Rihanna, Drake",2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,Shape of You,Ed Sheeran,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,Despacito,"Luis Fonsi, Daddy Yankee",2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,HUMBLE.,Kendrick Lamar,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,God's Plan,Drake,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,"thank u, next",Ariana Grande,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,Shallow,"Lady Gaga, Bradley Cooper",2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,Old Town Road,"Lil Nas X, Billy Ray Cyrus",2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,bad guy,Billie Eilish,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,Blinding Lights,The Weeknd,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,Watermelon Sugar,Harry Styles,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,Levitating,Dua Lipa,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,WAP,"Cardi B, Megan Thee Stallion",2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,drivers license,Olivia Rodrigo,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,STAY,"The Kid LAROI, Justin Bieber",2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,MONTERO (Call Me By Your Name),Lil Nas X,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,As It Was,Harry Styles,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,Anti-Hero,Taylor Swift,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,Kill Bill,SZA,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,Flowers,Miley Cyrus,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,Paint The Town Red,Doja Cat,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,vampire,Olivia Rodrigo,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,Not Like Us,Kendrick Lamar,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,Espresso,Sabrina Carpenter,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,A Bar Song (Tipsy),Shaboozey,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,Die With A Smile,"Lady Gaga, Bruno Mars",2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,luther,"Kendrick Lamar, SZA",2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,Ordinary,Alex Warren,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
def fetch_spotify_id(row):
    # Convert to string in case of missing data (NaN)
    song = str(row['Song']) 
    artist = str(row['Artist'])
    
    # Format the query specifically for the Spotify search engine
    query = f"track:{song} artist:{artist}"
    
    try:
        # Search for 1 track matching the query
        results = sp.search(q=query, type='track', limit=1)
        items = results['tracks']['items']
        
        # If the list is not empty, extract the ID
        if items:
            return items[0]['id']
        else:
            print(f"No match found for: {song} by {artist}")
            return None
            
    except Exception as e:
        print(f"API Error fetching {song}: {e}")
        return None

In [3]:
music_data['SONG_ID'] = music_data.apply(fetch_spotify_id, axis=1)
music_data

,Song,Artist,Release_Year,Violence,Heartbreak,Partying,Drugs,Sex,Self-Empowerment,Success,Hope,Celebration,Coming_Of_Age,Loneliness,Struggle,Love,Friendship,Traveling,SONG_ID
0,Vogue,Madonna,1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7j5TIXPi0cCbSSqItmbyZy
1,Enjoy the Silence,Depeche Mode,1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0yp3TvJNlG50Q4tAHWNCRm
2,Ice Ice Baby,Vanilla Ice,1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3XVozq1aeqsJwpXrEZrDJ9
3,Smells Like Teen Spirit,Nirvana,1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5ghIJDpPoe3CfHMGu71E6T
4,Losing My Religion,R.E.M.,1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31AOj9sFz2gM0O3hMARRBx
5,Black or White,Michael Jackson,1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7EsjkelQuoUlJXEw7SeVV4
6,I Will Always Love You,Whitney Houston,1992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4eHbdreAnSOrDDsFfc4Fpm
7,Creep,Radiohead,1992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70LcF31zb1H0PyJoS1Sx1r
8,Baby Got Back,Sir Mix-a-Lot,1992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1SAkL1mYNJlaqnBQxVZrRl
9,What Is Love,Haddaway,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0OTO8ZF2YqFQVw9hnZylTd
10,C.R.E.A.M.,Wu-Tang Clan,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119c93MHjrDLJTApCVGpvx
11,All That She Wants,Ace of Base,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6kWJvPfC4DgUpRsXKNa9z9
12,Basket Case,Green Day,1994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6L89mwZXSOwYl76YXfX13s
13,Black Hole Sun,Soundgarden,1994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2EoOZnxNgtmZaD8uUmz2nD
14,All I Want for Christmas Is You,Mariah Carey,1994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0bYg9bo50gSsH3LtXe2SQn
15,Wonderwall,Oasis,1995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7ygpwy2qP3NbrxVkHvUhXY
16,Gangsta's Paradise,"Coolio, L.V.",1995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1DIXPcTDzTj8ZMHt3PDt8p
17,Waterfalls,TLC,1995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6qspW4YKycviDFjHBOaqUY
18,Wannabe,Spice Girls,1996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1Je1IMUlBXcx1Fz0WE7oPT
19,California Love,"2Pac, Dr. Dre",1996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3ia3dJETSOllPsv3LJkE35
20,Don't Speak,No Doubt,1996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6urCAbunOQI4bLhmGpX7iS
21,My Heart Will Go On,Céline Dion,1997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33LC84JgLvK2KuW43MfaNq
22,Bitter Sweet Symphony,The Verve,1997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57iDDD9N9tTWe75x6qhStw
23,Barbie Girl,Aqua,1997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5ZrDlcxIDZyjOzHdYW1ydr
24,...Baby One More Time,Britney Spears,1998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3MjUtNVVq3C8Fn0MP3zhXa
25,The Boy Is Mine,"Brandy, Monica",1998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6sHsXIJoEN5JpdkGMQDJxt
26,I Don't Want to Miss a Thing,Aerosmith,1998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5qlJg0Wbj3sslxfwiaRNpq
27,I Want It That Way,Backstreet Boys,1999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47BBI51FKFwOMlIiX6m8ya
28,No Scrubs,TLC,1999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1KGi9sZVMeszgZOWivFpxs
29,Smooth,"Santana, Rob Thomas",1999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2pX4FpOgwItRVPPUFdRcxA
30,Oops!... I Did It Again,Britney Spears,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6naxalmIoLFWR0siv8dnQQ
31,Bye Bye Bye,*NSYNC,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62bOmKYxYg7dhrC6gH9vFn
32,Stan,"Eminem, Dido",2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3UmaczJpikHgJFyBTAJVoz
33,In the End,Linkin Park,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60a0Rd6pjrkxjPbaKzXjfq
34,How You Remind Me,Nickelback,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0gmbgwZ8iqyMPmXefof8Yf
35,Fallin',Alicia Keys,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0KQx6HOpJueiSkztcS0r7D
36,Lose Yourself,Eminem,2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5Z01UMMf7V1o0MzF86s6WJ
37,Complicated,Avril Lavigne,2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5xEM5hIgJ1jjgcEBfpkt2F
38,Hot in Herre,Nelly,2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04KTF78FFg8sOHC1BADqbY
39,Crazy in Love,"Beyoncé, JAY-Z",2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5IVuqXILoxVWvWEPm82Jxr
40,Hey Ya!,Outkast,2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2PpruBYCo4H7WOBJ7Q2EwM
41,In da Club,50 Cent,2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4RY96Asd9IefaL3X4LOLZ8
42,Yeah!,"Usher, Lil Jon, Ludacris",2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5rb9QrpfcKFHM1EUbSIurX
43,Mr. Brightside,The Killers,2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,003vvx7Niy0yvhvHt4a68B
44,Toxic,Britney Spears,2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6I9VzXrHxO9rA9A5euc8Ak
45,Gold Digger,"Kanye West, Jamie Foxx",2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1PS1QMdUqOal0ai3Gt7sDQ
46,We Belong Together,Mariah Carey,2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3LmvfNUQtglbTrydsdIqFU
47,Feel Good Inc.,Gorillaz,2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0d28khcov6AiegSCpG5TuT
48,Hips Don't Lie,"Shakira, Wyclef Jean",2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3d0WouFnFmr0K3kjeza3fF
49,SexyBack,Justin Timberlake,2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0O45fw2L5vsWpdsOdXwNAR
50,Crazy,Gnarls Barkley,2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6o1l9I0faXJN2iqulHrdCQ
51,Umbrella,"Rihanna, JAY-Z",2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2yPoXCs7BSIUrucMdK5PzV
52,Stronger,Kanye West,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0j2T0R9dR9qdJYsB7ciXhf
53,Crank That (Soulja Boy),Soulja Boy,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66TRwr5uJwPt15mfFkzhbi
54,Viva La Vida,Coldplay,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1mea3bSkSGXuIRvnydlB5b
55,Single Ladies (Put a Ring on It),Beyoncé,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2ZBNclC5wm4GtiWaeh0DMx
56,Poker Face,Lady Gaga,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5R8dQOPq8haW94K7mgERlO
57,I Gotta Feeling,Black Eyed Peas,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2H1047e0oMSj10dgp7p2VG
58,Bad Romance,Lady Gaga,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0SiywuOBRcynK0uKGWdCnn
59,Tik Tok,Kesha,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0HPD5WQqrq7wPWR7P7Dw1i
60,Rolling in the Deep,Adele,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1c8gk2PeTE04A1pIDH9YMk
61,Teenage Dream,Katy Perry,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5jzKL4BDMClWqRguW5qZvh
62,Love the Way You Lie,"Eminem, Rihanna",2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15JINEqzVMv3SvJTAXAKED
63,Somebody That I Used to Know,"Gotye, Kimbra",2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4wCmqSrbyCgxEXROQE6vtV
64,Party Rock Anthem,LMFAO,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0IkKz2J93C94Ei4BvDop7P
65,We Found Love,"Rihanna, Calvin Harris",2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6qn9YLKt13AGvpq9jfO8py
66,Gangnam Style,PSY,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03UrZgTINDqvnUMbbIMhql
67,Call Me Maybe,Carly Rae Jepsen,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3TGRqZ0a2l1LRblBkJoaDx
68,Thrift Shop,"Macklemore, Ryan Lewis",2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6CjtS2JZH9RkDz5UVInsa9
69,Get Lucky,"Daft Punk, Pharrell Williams",2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69kOkLUCkxIZYexIgSG8rq
70,Royals,Lorde,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2dLLR6qlu5UJ5gk0dKz0h3
71,Wake Me Up,Avicii,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0nrRP2bk19rLc0orkWPQk2
72,Uptown Funk,"Mark Ronson, Bruno Mars",2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32OlwWuMpZ6b0aN2RZOeMS
73,Shake It Off,Taylor Swift,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5xTtaWoae3wi06K5WfVUUH
74,Thinking Out Loud,Ed Sheeran,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1Slwb6dOYkBlWal1PGtnNg
75,Hello,Adele,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62PaSfnXSMyLshYJrlTuL3
76,Hotline Bling,Drake,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0wwPcA6wtMf6HUMpIRdeP7
77,See You Again,"Wiz Khalifa, Charlie Puth",2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2JzZzZUQj3Qff7wapcbKjc
78,Closer,"The Chainsmokers, Halsey",2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7BKLCZ1jbUBVqRi2FVlTVw
79,Starboy,"The Weeknd, Daft Punk",2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7MXVkk9YMctZqd1Srtv4MB
80,Work,"Rihanna, Drake",2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72TFWvU3wUYdUuxejTTIzt
81,Shape of You,Ed Sheeran,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7qiZfU4dY1lWllzX7mPBI3
82,Despacito,"Luis Fonsi, Daddy Yankee",2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6habFhsOp2NvshLv26DqMb
83,HUMBLE.,Kendrick Lamar,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7KXjTSCq5nL1LoYtL7XAwS
84,God's Plan,Drake,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6DCZcSspjsKoFjzjrWoCdn
85,"thank u, next",Ariana Grande,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3e9HZxeyfWwjeyPAMmWSSQ
86,Shallow,"Lady Gaga, Bradley Cooper",2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2VxeLyX666F8uXCJ0dZF8B
87,Old Town Road,"Lil Nas X, Billy Ray Cyrus",2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2YpeDb67231RjR0MgVLzsG
88,bad guy,Billie Eilish,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2Fxmhks0bxGSBdJ92vM42m
89,Blinding Lights,The Weeknd,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0VjIjW4GlUZAMYd2vXMi3b
90,Watermelon Sugar,Harry Styles,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6UelLqGlWMcVH1E5c4H7lY
91,Levitating,Dua Lipa,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5nujrmhLynf4yMoMtj8AQF
92,WAP,"Cardi B, Megan Thee Stallion",2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4Oun2ylbjFKMPTiaSbbCih
93,drivers license,Olivia Rodrigo,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5wANPM4fQCJwkGd4rN57mH
94,STAY,"The Kid LAROI, Justin Bieber",2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,567e29TDzLwZwfDuEpGTwo
95,MONTERO (Call Me By Your Name),Lil Nas X,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1SC5rEoYDGUK4NfG82494W
96,As It Was,Harry Styles,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4Dvkj6JhhA12EX05fT7y2e
97,Anti-Hero,Taylor Swift,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0V3wPSX9ygBnCm8psDIegu
98,Kill Bill,SZA,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1Qrg8KqiBpW07V7PNxwwwL
99,Flowers,Miley Cyrus,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7DSAEUvxU8FajXtRloy8M0
100,Paint The Town Red,Doja Cat,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2IGMVunIBsBLtEQyoI1Mu7
101,vampire,Olivia Rodrigo,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1kuGVB7EU95pJObxwvfwKS
102,Not Like Us,Kendrick Lamar,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6AI3ezQ4o3HUoP6Dhudph3
103,Espresso,Sabrina Carpenter,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2HRqTpkrJO5ggZyyK6NPWz
104,A Bar Song (Tipsy),Shaboozey,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5fZJQrFKWQLb7FpJXZ1g7K
105,Die With A Smile,"Lady Gaga, Bruno Mars",2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2plbrEY59IikOBgBGLjaoe
106,luther,"Kendrick Lamar, SZA",2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2CGNAOSuO1MEFCbBRgUzjd
107,Ordinary,Alex Warren,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2RkZ5LkEzeHGRsmDqKwmaJ

In [ ]:
import time
import requests

# Ensure your RapidAPI key is loaded
load_dotenv()
RAPIDAPI_KEY = os.getenv('RAPIDAPI_KEY')

def fetch_all_soundnet_features(row):
    # Grab the Spotify ID we generated earlier
    spotify_id = row.get('SONG_ID')
    
    # Define the exact columns we expect to create
    feature_columns = [
        'SoundNet_ID', 'Key', 'Mode', 'Camelot', 
        'Tempo', 'Duration', 'Popularity', 'Energy', 'Danceability', 
        'Happiness', 'Acousticness', 'Instrumentalness', 'Liveness', 
        'Speechiness', 'Loudness'
    ]
    
    # If there is no ID, return a row of empty values
    if pd.isna(spotify_id) or not spotify_id:
        return pd.Series({col: None for col in feature_columns})

    # The API endpoint
    url = f"https://track-analysis.p.rapidapi.com/pktx/spotify/{spotify_id}"
    
    headers = {
        "x-rapidapi-key": RAPIDAPI_KEY,
        "x-rapidapi-host": "track-analysis.p.rapidapi.com"
    }
    
    try:
        response = requests.get(url, headers=headers)
        
        if response.status_code == 200:
            data = response.json()
            
            # Rate limiting sleep (1 second between successful calls)
            time.sleep(1)
            
            # Map the JSON data directly into a pandas Series
            return pd.Series({
                'SoundNet_ID': data.get('id'),
                'Key': data.get('key'),
                'Mode': data.get('mode'),
                'Camelot': data.get('camelot'),
                'Tempo': data.get('tempo'),
                'Duration': data.get('duration'),
                'Popularity': data.get('popularity'),
                'Energy': data.get('energy'),
                'Danceability': data.get('danceability'),
                'Happiness': data.get('happiness'),
                'Acousticness': data.get('acousticness'),
                'Instrumentalness': data.get('instrumentalness'),
                'Liveness': data.get('liveness'),
                'Speechiness': data.get('speechiness'),
                'Loudness': data.get('loudness')
            })
        else:
            print(f"API Error {response.status_code} for ID {spotify_id}: {response.text}")
            
    except Exception as e:
        print(f"Network error for ID {spotify_id}: {e}")
    
    # Fallback rate limiting in case of errors
    time.sleep(1) 
    
    # Return empty data if the API call failed
    return pd.Series({col: None for col in feature_columns})

In [5]:
print("Fetching comprehensive audio features from SoundNet...")
new_audio_features = music_data.apply(fetch_all_soundnet_features, axis=1)

# 5. Add the new columns to the dataframe
print("Merging new columns into the dataset...")
music_data = pd.concat([music_data, new_audio_features], axis=1)

music_data

Fetching comprehensive audio features from SoundNet...
Merging new columns into the dataset...

,Song,Artist,Release_Year,Violence,Heartbreak,Partying,Drugs,Sex,Self-Empowerment,Success,Hope,Celebration,Coming_Of_Age,Loneliness,Struggle,Love,Friendship,Traveling,SONG_ID,SoundNet_ID,Track_Name,Album,Key,Mode,Camelot,Tempo,Duration,Popularity,Energy,Danceability,Happiness,Acousticness,Instrumentalness,Liveness,Speechiness,Loudness
0,Vogue,Madonna,1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7j5TIXPi0cCbSSqItmbyZy,dm9ndWUtbWFkb25uYQ==,None,None,D#,minor,2A,116,5:17,68,84,75,31,0,1,44,4,-8 dB
1,Enjoy the Silence,Depeche Mode,1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0yp3TvJNlG50Q4tAHWNCRm,ZW5qb3ktdGhlLXNpbGVuY2UtZGVwZWNoZS1tb2Rl,None,None,C,minor,5A,113,4:15,76,84,66,75,20,0,8,3,-6 dB
2,Ice Ice Baby,Vanilla Ice,1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3XVozq1aeqsJwpXrEZrDJ9,aWNlLWljZS1iYWJ5LXZhbmlsbGEtaWNl,None,None,D,major,10B,116,4:14,72,79,98,58,0,0,10,4,-3 dB
3,Smells Like Teen Spirit,Nirvana,1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5ghIJDpPoe3CfHMGu71E6T,c21lbGxzLWxpa2UtdGVlbi1zcGlyaXQtbmlydmFuYQ==,None,None,C#,major,3B,117,5:02,83,91,50,72,0,0,11,6,-5 dB
4,Losing My Religion,R.E.M.,1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31AOj9sFz2gM0O3hMARRBx,bG9zaW5nLW15LXJlbGlnaW9uLXJlbQ==,None,None,A,minor,8A,126,4:28,88,86,67,80,18,0,10,3,-5 dB
5,Black or White,Michael Jackson,1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7EsjkelQuoUlJXEw7SeVV4,YmxhY2stb3Itd2hpdGUtbWljaGFlbC1qYWNrc29u,None,None,A,major,11B,115,4:16,77,90,52,87,17,3,7,9,-4 dB
6,I Will Always Love You,Whitney Houston,1992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4eHbdreAnSOrDDsFfc4Fpm,aS13aWxsLWFsd2F5cy1sb3ZlLXlvdS13aGl0bmV5LWhvdX...,None,None,E,major,12B,68,4:31,80,21,33,11,85,0,8,3,-13 dB
7,Creep,Radiohead,1992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70LcF31zb1H0PyJoS1Sx1r,Y3JlZXAtcmFkaW9oZWFk,None,None,G,major,9B,92,3:59,93,43,52,10,1,0,13,4,-10 dB
8,Baby Got Back,Sir Mix-a-Lot,1992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1SAkL1mYNJlaqnBQxVZrRl,YmFieS1nb3QtYmFjay1zaXItbWl4YWxvdA==,None,None,C#,major,3B,128,4:23,75,67,93,64,1,0,9,30,-11 dB
9,What Is Love,Haddaway,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0OTO8ZF2YqFQVw9hnZylTd,d2hhdC1pcy1sb3ZlLTdxdW90LW1peC1oYWRkYXdheQ==,None,None,G,minor,6A,124,4:30,67,77,68,74,2,2,20,3,-8 dB
10,C.R.E.A.M.,Wu-Tang Clan,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119c93MHjrDLJTApCVGpvx,Y3JlYW0tY2FzaC1ydWxlcy1ldmVyeXRoaW5nLWFyb3VuZC...,None,None,B,minor,10A,181,4:12,76,51,51,56,56,1,13,39,-12 dB
11,All That She Wants,Ace of Base,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6kWJvPfC4DgUpRsXKNa9z9,YWxsLXRoYXQtc2hlLXdhbnRzLWFjZS1vZi1iYXNl,None,None,B,major,1B,94,3:31,82,63,80,86,1,0,10,5,-10 dB
12,Basket Case,Green Day,1994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6L89mwZXSOwYl76YXfX13s,YmFza2V0LWNhc2UtZ3JlZW4tZGF5,None,None,Eb,major,5B,85,3:02,86,94,44,78,0,0,9,6,-3 dB
13,Black Hole Sun,Soundgarden,1994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2EoOZnxNgtmZaD8uUmz2nD,YmxhY2staG9sZS1zdW4tc291bmRnYXJkZW4=,None,None,F#,major,2B,105,5:19,80,83,35,15,0,0,8,4,-5 dB
14,All I Want for Christmas Is You,Mariah Carey,1994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0bYg9bo50gSsH3LtXe2SQn,YWxsLWktd2FudC1mb3ItY2hyaXN0bWFzLWlzLXlvdS1tYX...,None,None,G,major,9B,150,4:02,75,63,34,35,16,0,7,4,-7 dB
15,Wonderwall,Oasis,1995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7ygpwy2qP3NbrxVkHvUhXY,d29uZGVyd2FsbC1yZW1hc3RlcmVkLW9hc2lz,None,None,D,major,10B,174,4:19,80,89,38,43,0,0,19,4,-4 dB
16,Gangsta's Paradise,"Coolio, L.V.",1995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1DIXPcTDzTj8ZMHt3PDt8p,Z2FuZ3N0YXgyN3MtcGFyYWRpc2UtY29vbGlvLWx2,None,None,Ab,major,4B,80,4:01,88,51,65,39,7,0,40,6,-10 dB
17,Waterfalls,TLC,1995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6qspW4YKycviDFjHBOaqUY,d2F0ZXJmYWxscy10bGM=,None,None,C#,major,3B,172,4:40,77,51,77,76,31,0,8,8,-7 dB
18,Wannabe,Spice Girls,1996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1Je1IMUlBXcx1Fz0WE7oPT,d2FubmFiZS1zcGljZS1naXJscw==,None,None,B,major,1B,110,2:53,84,86,77,89,10,0,16,3,-6 dB
19,California Love,"2Pac, Dr. Dre",1996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3ia3dJETSOllPsv3LJkE35,Y2FsaWZvcm5pYS1sb3ZlLW9yaWdpbmFsLXZlcnNpb24tMn...,None,None,G,major,9B,92,4:45,82,85,76,76,3,0,37,4,-3 dB
20,Don't Speak,No Doubt,1996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6urCAbunOQI4bLhmGpX7iS,ZG9ueDI3dC1zcGVhay1uby1kb3VidA==,None,None,F,minor,4A,76,4:23,62,75,51,55,25,0,14,3,-5 dB
21,My Heart Will Go On,Céline Dion,1997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33LC84JgLvK2KuW43MfaNq,bXktaGVhcnQtd2lsbC1nby1vbi1sb3ZlLXRoZW1lLWZyb2...,None,None,E,major,12B,99,4:40,75,28,43,4,73,0,12,3,-12 dB
22,Bitter Sweet Symphony,The Verve,1997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57iDDD9N9tTWe75x6qhStw,Yml0dGVyLXN3ZWV0LXN5bXBob255LXJlbWFzdGVyZWQtMj...,None,None,A,major,11B,171,5:57,85,92,36,52,3,0,41,5,-6 dB
23,Barbie Girl,Aqua,1997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5ZrDlcxIDZyjOzHdYW1ydr,YmFyYmllLWdpcmwtYXF1YQ==,None,None,C#,minor,12A,130,3:18,78,88,81,96,2,22,37,4,-11 dB
24,...Baby One More Time,Britney Spears,1998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3MjUtNVVq3C8Fn0MP3zhXa,YmFieS1vbmUtbW9yZS10aW1lLWJyaXRuZXktc3BlYXJz,None,None,C,minor,5A,93,3:31,86,70,76,91,20,0,44,3,-6 dB
25,The Boy Is Mine,"Brandy, Monica",1998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6sHsXIJoEN5JpdkGMQDJxt,dGhlLWJveS1pcy1taW5lLWJyYW5keS1tb25pY2E=,None,None,C#,minor,12A,93,4:55,78,71,70,76,54,0,32,4,-7 dB
26,I Don't Want to Miss a Thing,Aerosmith,1998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5qlJg0Wbj3sslxfwiaRNpq,aS1kb254Mjd0LXdhbnQtdG8tbWlzcy1hLXRoaW5nLWZyb2...,None,None,D,major,10B,121,4:59,77,66,38,14,17,0,25,3,-5 dB
27,I Want It That Way,Backstreet Boys,1999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47BBI51FKFwOMlIiX6m8ya,aS13YW50LWl0LXRoYXQtd2F5LWJhY2tzdHJlZXQtYm95cw==,None,None,F#,minor,11A,99,3:33,86,69,69,48,26,0,15,3,-6 dB
28,No Scrubs,TLC,1999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1KGi9sZVMeszgZOWivFpxs,bm8tc2NydWJzLXRsYw==,None,None,G#,minor,1A,93,3:34,85,68,74,59,3,0,7,10,-4 dB
29,Smooth,"Santana, Rob Thomas",1999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2pX4FpOgwItRVPPUFdRcxA,c21vb3RoLWZlYXQtcm9iLXRob21hcy1zYW50YW5hLXJvYi...,None,None,A,major,11B,116,4:55,73,92,61,96,16,0,30,3,-4 dB
30,Oops!... I Did It Again,Britney Spears,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6naxalmIoLFWR0siv8dnQQ,b29wc2ktZGlkLWl0LWFnYWluLWJyaXRuZXktc3BlYXJz,None,None,C#,minor,12A,95,3:31,83,83,75,89,30,0,36,4,-5 dB
31,Bye Bye Bye,*NSYNC,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62bOmKYxYg7dhrC6gH9vFn,YnllLWJ5ZS1ieWUtbnN5bmM=,None,None,G#,minor,1A,173,3:20,81,93,61,86,3,0,8,5,-5 dB
32,Stan,"Eminem, Dido",2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3UmaczJpikHgJFyBTAJVoz,c3Rhbi1lbWluZW0tZGlkbw==,None,None,F#,minor,11A,80,6:44,83,77,78,51,4,0,52,24,-4 dB
33,In the End,Linkin Park,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60a0Rd6pjrkxjPbaKzXjfq,aW4tdGhlLWVuZC1saW5raW4tcGFyaw==,None,None,D#,minor,2A,105,3:37,91,86,56,40,1,0,21,6,-6 dB
34,How You Remind Me,Nickelback,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0gmbgwZ8iqyMPmXefof8Yf,aG93LXlvdS1yZW1pbmQtbWUtbmlja2VsYmFjaw==,None,None,Bb,major,6B,172,3:44,88,76,45,54,0,0,10,3,-5 dB
35,Fallin',Alicia Keys,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0KQx6HOpJueiSkztcS0r7D,ZmFsbGlueDI3LWFsaWNpYS1rZXlz,None,None,B,minor,10A,96,3:30,81,61,65,48,26,0,23,4,-8 dB
36,Lose Yourself,Eminem,2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5Z01UMMf7V1o0MzF86s6WJ,bG9zZS15b3Vyc2VsZi1lbWluZW0=,None,None,D,major,10B,171,5:26,81,74,69,6,1,0,36,26,-5 dB
37,Complicated,Avril Lavigne,2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5xEM5hIgJ1jjgcEBfpkt2F,Y29tcGxpY2F0ZWQtYXZyaWwtbGF2aWduZQ==,None,None,F,major,7B,78,4:05,86,78,59,43,6,0,30,5,-6 dB
38,Hot in Herre,Nelly,2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04KTF78FFg8sOHC1BADqbY,aG90LWluLWhlcnJlLW5lbGx5,None,None,B,minor,10A,107,3:48,80,74,96,91,20,0,6,12,-5 dB
39,Crazy in Love,"Beyoncé, JAY-Z",2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5IVuqXILoxVWvWEPm82Jxr,Y3JhenktaW4tbG92ZS1mZWF0LWpheXotYmV5b25jLWpheg==,None,None,D,minor,7A,99,3:56,81,77,65,68,0,0,7,23,-7 dB
40,Hey Ya!,Outkast,2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2PpruBYCo4H7WOBJ7Q2EwM,aGV5LXlhLW91dGthc3Q=,None,None,E,minor,9A,80,3:55,84,97,73,97,10,0,17,7,-2 dB
41,In da Club,50 Cent,2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4RY96Asd9IefaL3X4LOLZ8,aW4tZGEtY2x1Yi01MC1jZW50,None,None,F#,minor,11A,90,3:13,78,72,90,81,26,0,7,35,-3 dB
42,Yeah!,"Usher, Lil Jon, Ludacris",2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5rb9QrpfcKFHM1EUbSIurX,eWVhaC1mZWF0LWxpbC1qb24tYW1wLWx1ZGFjcmlzLXVzaG...,None,None,D,major,10B,105,4:10,87,79,89,58,2,0,4,11,-5 dB
43,Mr. Brightside,The Killers,2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,003vvx7Niy0yvhvHt4a68B,bXItYnJpZ2h0c2lkZS10aGUta2lsbGVycw==,None,None,C#,major,3B,148,3:43,91,91,35,24,0,0,10,7,-5 dB
44,Toxic,Britney Spears,2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6I9VzXrHxO9rA9A5euc8Ak,dG94aWMtYnJpdG5leS1zcGVhcnM=,None,None,F,minor,4A,143,3:19,86,84,77,92,2,3,24,11,-4 dB
45,Gold Digger,"Kanye West, Jamie Foxx",2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1PS1QMdUqOal0ai3Gt7sDQ,Z29sZC1kaWdnZXIta2FueWUtd2VzdC1qYW1pZS1mb3h4,None,None,C#,minor,12A,93,3:28,82,70,63,62,2,0,6,35,-6 dB
46,We Belong Together,Mariah Carey,2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3LmvfNUQtglbTrydsdIqFU,d2UtYmVsb25nLXRvZ2V0aGVyLW1hcmlhaC1jYXJleQ==,None,None,C,major,8B,140,3:21,73,47,83,77,3,0,9,6,-8 dB
47,Feel Good Inc.,Gorillaz,2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0d28khcov6AiegSCpG5TuT,ZmVlbC1nb29kLWluYy1nb3JpbGxhei1kZS1sYS1zb3Vs,None,None,F#,major,2B,139,3:43,92,71,82,77,1,0,61,18,-7 dB
48,Hips Don't Lie,"Shakira, Wyclef Jean",2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3d0WouFnFmr0K3kjeza3fF,aGlwcy1kb254Mjd0LWxpZS1mZWF0LXd5Y2xlZi1qZWFuLX...,None,None,A#,minor,3A,100,3:40,89,82,78,76,28,0,36,7,-6 dB
49,SexyBack,Justin Timberlake,2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0O45fw2L5vsWpdsOdXwNAR,c2V4eWJhY2stZmVhdC10aW1iYWxhbmQtanVzdGluLXRpbW...,None,None,G,minor,6A,117,4:03,87,58,97,96,6,0,5,8,-6 dB
50,Crazy,Gnarls Barkley,2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6o1l9I0faXJN2iqulHrdCQ,Y3JhenktZ25hcmxzLWJhcmtsZXktY2VlbG8tZ3JlZW4tZG...,None,None,Ab,major,4B,112,3:02,77,74,84,61,2,6,8,3,-2 dB
51,Umbrella,"Rihanna, JAY-Z",2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2yPoXCs7BSIUrucMdK5PzV,dW1icmVsbGEtcmloYW5uYS1qYXo=,None,None,C#,major,3B,174,4:36,86,83,59,58,1,0,4,12,-5 dB
52,Stronger,Kanye West,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0j2T0R9dR9qdJYsB7ciXhf,c3Ryb25nZXIta2FueWUtd2VzdA==,None,None,C#,major,3B,104,5:12,86,72,62,50,1,0,41,14,-8 dB
53,Crank That (Soulja Boy),Soulja Boy,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66TRwr5uJwPt15mfFkzhbi,Y3JhbmstdGhhdC1zb3VsamEtYm95LXNvdWxqYS1ib3k=,None,None,C,major,8B,140,3:42,78,74,73,80,51,0,5,9,-2 dB
54,Viva La Vida,Coldplay,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1mea3bSkSGXuIRvnydlB5b,dml2YS1sYS12aWRhLWNvbGRwbGF5,None,None,F,minor,4A,138,4:02,89,62,49,42,10,0,11,3,-7 dB
55,Single Ladies (Put a Ring on It),Beyoncé,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2ZBNclC5wm4GtiWaeh0DMx,c2luZ2xlLWxhZGllcy1wdXQtYS1yaW5nLW9uLWl0LWJleW...,None,None,C#,major,3B,193,3:13,69,58,43,27,4,0,19,30,-5 dB
56,Poker Face,Lady Gaga,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5R8dQOPq8haW94K7mgERlO,cG9rZXItZmFjZS1sYWR5LWdhZ2E=,None,None,E,major,12B,119,3:57,82,81,85,77,12,0,12,8,-5 dB
57,I Gotta Feeling,Black Eyed Peas,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2H1047e0oMSj10dgp7p2VG,aS1nb3R0YS1mZWVsaW5nLWJsYWNrLWV5ZWQtcGVhcw==,None,None,C,major,8B,128,4:49,80,77,74,61,9,0,51,3,-6 dB
58,Bad Romance,Lady Gaga,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0SiywuOBRcynK0uKGWdCnn,YmFkLXJvbWFuY2UtbGFkeS1nYWdh,None,None,C,major,8B,119,4:54,51,92,69,71,0,0,9,4,-4 dB
59,Tik Tok,Kesha,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0HPD5WQqrq7wPWR7P7Dw1i,dGlrLXRvay1rZXNoYQ==,None,None,D,minor,7A,120,3:20,87,84,76,71,10,0,29,14,-3 dB
60,Rolling in the Deep,Adele,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1c8gk2PeTE04A1pIDH9YMk,cm9sbGluZy1pbi10aGUtZGVlcC1hZGVsZQ==,None,None,Ab,major,4B,105,3:48,78,77,73,51,14,0,5,3,-5 dB
61,Teenage Dream,Katy Perry,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5jzKL4BDMClWqRguW5qZvh,dGVlbmFnZS1kcmVhbS1rYXR5LXBlcnJ5,None,None,Bb,major,6B,120,3:48,75,80,72,59,2,0,13,4,-5 dB
62,Love the Way You Lie,"Eminem, Rihanna",2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15JINEqzVMv3SvJTAXAKED,bG92ZS10aGUtd2F5LXlvdS1saWUtZW1pbmVtLXJpaGFubmE=,None,None,Bb,major,6B,87,4:23,89,93,75,64,24,0,52,23,-5 dB
63,Somebody That I Used to Know,"Gotye, Kimbra",2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4wCmqSrbyCgxEXROQE6vtV,c29tZWJvZHktdGhhdC1pLXVzZWQtdG8ta25vdy1nb3R5ZS...,None,None,C,major,8B,129,4:05,79,50,86,72,59,0,10,4,-7 dB
64,Party Rock Anthem,LMFAO,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0IkKz2J93C94Ei4BvDop7P,cGFydHktcm9jay1hbnRoZW0tbG1mYW8tbGF1cmVuLWJlbm...,None,None,F,minor,4A,130,4:22,73,73,75,36,2,0,27,14,-4 dB
65,We Found Love,"Rihanna, Calvin Harris",2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6qn9YLKt13AGvpq9jfO8py,d2UtZm91bmQtbG92ZS1yaWhhbm5hLWNhbHZpbi1oYXJyaXM=,None,None,C#,major,3B,128,3:35,87,77,74,60,3,0,11,4,-4 dB
66,Gangnam Style,PSY,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03UrZgTINDqvnUMbbIMhql,Z2FuZ25hbS1zdHlsZS1wc3k=,None,None,B,minor,10A,132,3:39,78,94,73,75,0,0,9,29,-3 dB
67,Call Me Maybe,Carly Rae Jepsen,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3TGRqZ0a2l1LRblBkJoaDx,Y2FsbC1tZS1tYXliZS1jYXJseS1yYWUtamVwc2Vu,None,None,G,major,9B,120,3:13,74,58,78,66,1,0,11,4,-7 dB
68,Thrift Shop,"Macklemore, Ryan Lewis",2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6CjtS2JZH9RkDz5UVInsa9,dGhyaWZ0LXNob3AtZmVhdC13YW56LW1hY2tsZW1vcmUtYW...,None,None,F#,minor,11A,95,3:56,69,53,78,66,6,0,5,29,-7 dB
69,Get Lucky,"Daft Punk, Pharrell Williams",2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69kOkLUCkxIZYexIgSG8rq,Z2V0LWx1Y2t5LWZlYXQtcGhhcnJlbGwtd2lsbGlhbXMtYW...,None,None,F#,minor,11A,116,6:10,77,79,81,86,4,0,7,4,-9 dB
70,Royals,Lorde,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2dLLR6qlu5UJ5gk0dKz0h3,cm95YWxzLWxvcmRl,None,None,G,major,9B,85,3:10,62,43,67,34,12,0,13,12,-10 dB
71,Wake Me Up,Avicii,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0nrRP2bk19rLc0orkWPQk2,d2FrZS1tZS11cC1hdmljaWk=,None,None,D,major,10B,124,4:07,87,78,53,64,0,0,16,5,-6 dB
72,Uptown Funk,"Mark Ronson, Bruno Mars",2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32OlwWuMpZ6b0aN2RZOeMS,dXB0b3duLWZ1bmstZmVhdC1icnVuby1tYXJzLW1hcmstcm...,None,None,C,major,8B,115,4:30,86,61,86,93,1,0,3,8,-7 dB
73,Shake It Off,Taylor Swift,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5xTtaWoae3wi06K5WfVUUH,c2hha2UtaXQtb2ZmLXRheWxvci1zd2lmdA==,None,None,G,major,9B,160,3:39,75,79,65,94,6,0,15,17,-5 dB
74,Thinking Out Loud,Ed Sheeran,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1Slwb6dOYkBlWal1PGtnNg,dGhpbmtpbmctb3V0LWxvdWQtZWQtc2hlZXJhbg==,None,None,D,major,10B,79,4:42,86,45,78,59,47,0,18,3,-6 dB
75,Hello,Adele,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62PaSfnXSMyLshYJrlTuL3,aGVsbG8tYWRlbGU=,None,None,F,minor,4A,79,4:56,73,43,58,29,33,0,9,3,-6 dB
76,Hotline Bling,Drake,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0wwPcA6wtMf6HUMpIRdeP7,aG90bGluZS1ibGluZy1kcmFrZQ==,None,None,D,major,10B,135,4:27,84,63,89,55,0,0,5,6,-8 dB
77,See You Again,"Wiz Khalifa, Charlie Puth",2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2JzZzZUQj3Qff7wapcbKjc,c2VlLXlvdS1hZ2Fpbi1mZWF0LWNoYXJsaWUtcHV0aC13aX...,None,None,Bb,major,6B,80,3:50,84,48,69,28,37,0,6,8,-8 dB
78,Closer,"The Chainsmokers, Halsey",2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7BKLCZ1jbUBVqRi2FVlTVw,Y2xvc2VyLXRoZS1jaGFpbnNtb2tlcnMtaGFsc2V5,None,None,Ab,major,4B,95,4:05,88,52,75,66,41,0,11,3,-6 dB
79,Starboy,"The Weeknd, Daft Punk",2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7MXVkk9YMctZqd1Srtv4MB,c3RhcmJveS10aGUtd2Vla25kLWRhZnQtcHVuaw==,None,None,G,major,9B,186,3:50,92,59,68,49,14,0,14,28,-7 dB
80,Work,"Rihanna, Drake",2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72TFWvU3wUYdUuxejTTIzt,d29yay1yaWhhbm5hLWRyYWtl,None,None,B,major,1B,92,3:39,82,53,72,55,7,0,9,9,-6 dB
81,Shape of You,Ed Sheeran,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7qiZfU4dY1lWllzX7mPBI3,c2hhcGUtb2YteW91LWVkLXNoZWVyYW4=,None,None,C#,minor,12A,96,3:54,90,65,83,93,58,0,9,8,-3 dB
82,Despacito,"Luis Fonsi, Daddy Yankee",2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6habFhsOp2NvshLv26DqMb,ZGVzcGFjaXRvLWx1aXMtZm9uc2ktZGFkZHkteWFua2Vl,None,None,D,major,10B,178,3:49,82,80,66,84,20,0,7,15,-5 dB
83,HUMBLE.,Kendrick Lamar,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7KXjTSCq5nL1LoYtL7XAwS,aHVtYmxlLWtlbmRyaWNrLWxhbWFy,None,None,C#,minor,12A,150,2:57,85,62,91,42,0,0,10,10,-7 dB
84,God's Plan,Drake,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6DCZcSspjsKoFjzjrWoCdn,Z29keDI3cy1wbGFuLWRyYWtl,None,None,Ab,major,4B,85,3:13,1,50,67,39,36,0,14,6,-12 dB
85,"thank u, next",Ariana Grande,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3e9HZxeyfWwjeyPAMmWSSQ,dGhhbmstdS1uZXh0LWFyaWFuYS1ncmFuZGU=,None,None,C#,major,3B,107,3:27,84,65,72,41,23,0,10,6,-6 dB
86,Shallow,"Lady Gaga, Bradley Cooper",2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2VxeLyX666F8uXCJ0dZF8B,c2hhbGxvdy1sYWR5LWdhZ2EtYnJhZGxleS1jb29wZXI=,None,None,G,major,9B,96,3:36,84,39,58,33,37,0,23,3,-6 dB
87,Old Town Road,"Lil Nas X, Billy Ray Cyrus",2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2YpeDb67231RjR0MgVLzsG,b2xkLXRvd24tcm9hZC1mZWF0LWJpbGx5LXJheS1jeXJ1cy...,None,None,F#,major,2B,136,2:37,79,62,88,64,5,0,11,10,-6 dB
88,bad guy,Billie Eilish,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2Fxmhks0bxGSBdJ92vM42m,YmFkLWd1eS1iaWxsaWUtZWlsaXNo,None,None,G,major,9B,135,3:14,83,43,70,56,33,13,10,38,-11 dB
89,Blinding Lights,The Weeknd,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0VjIjW4GlUZAMYd2vXMi3b,YmxpbmRpbmctbGlnaHRzLXRoZS13ZWVrbmQ=,None,None,C#,major,3B,171,3:20,89,73,51,33,0,0,9,6,-6 dB
90,Watermelon Sugar,Harry Styles,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6UelLqGlWMcVH1E5c4H7lY,d2F0ZXJtZWxvbi1zdWdhci1oYXJyeS1zdHlsZXM=,None,None,C,major,8B,95,2:54,87,82,55,56,12,0,34,5,-4 dB

In [6]:
def fetch_lyrics(row):
    # Use your original Song and Artist columns for the search
    song = str(row['Song'])
    artist = str(row['Artist'])
    
    # Skip if missing data
    if pd.isna(song) or pd.isna(artist):
        return pd.Series({'Plain_Lyrics': None, 'Synced_Lyrics': None})

    # The LRCLIB Search Endpoint
    url = "https://lrclib.net/api/search"
    
    # requests will automatically format these into the URL
    params = {
        "track_name": song,
        "artist_name": artist
    }
    
    # The API docs politely ask for a User-Agent, so we will provide a generic one
    headers = {
        "User-Agent": "DataAnalysisScript/1.0"
    }

    try:
        response = requests.get(url, params=params, headers=headers)
        
        if response.status_code == 200:
            data = response.json()
            
            # The search API returns a list of matches. 
            # If the list is not empty, we take the top match (index 0).
            if len(data) > 0:
                top_match = data[0]
                return pd.Series({
                    'Plain_Lyrics': top_match.get('plainLyrics'),
                    'Synced_Lyrics': top_match.get('syncedLyrics')
                })
            else:
                print(f"No lyrics found for: {song} by {artist}")
        else:
            print(f"API Error {response.status_code} for {song}: {response.text}")
            
    except Exception as e:
        print(f"Network error fetching lyrics for {song}: {e}")
        
    # Politeness delay (even without rate limits, it's good practice)
    time.sleep(0.5)
    
    # Return empty if it fails
    return pd.Series({'Plain_Lyrics': None, 'Synced_Lyrics': None})

In [7]:
# 1. Execute the fetch row by row
print("Searching LRCLIB for lyrics...")
lyrics_features = music_data.apply(fetch_lyrics, axis=1)

# 2. Glue the new lyrics columns onto your dataset
music_data = pd.concat([music_data, lyrics_features], axis=1)

music_data

Searching LRCLIB for lyrics...

,Song,Artist,Release_Year,Violence,Heartbreak,Partying,Drugs,Sex,Self-Empowerment,Success,Hope,Celebration,Coming_Of_Age,Loneliness,Struggle,Love,Friendship,Traveling,SONG_ID,SoundNet_ID,Track_Name,Album,Key,Mode,Camelot,Tempo,Duration,Popularity,Energy,Danceability,Happiness,Acousticness,Instrumentalness,Liveness,Speechiness,Loudness,Plain_Lyrics,Synced_Lyrics
0,Vogue,Madonna,1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7j5TIXPi0cCbSSqItmbyZy,dm9ndWUtbWFkb25uYQ==,None,None,D#,minor,2A,116,5:17,68,84,75,31,0,1,44,4,-8 dB,What are you looking at?\n\nStrike a pose\n\nS...,[00:00.92] What are you looking at?\n[00:04.25...
1,Enjoy the Silence,Depeche Mode,1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0yp3TvJNlG50Q4tAHWNCRm,ZW5qb3ktdGhlLXNpbGVuY2UtZGVwZWNoZS1tb2Rl,None,None,C,minor,5A,113,4:15,76,84,66,75,20,0,8,3,-6 dB,Words like violence\nBreak the silence\nCome c...,[00:25.73] Words like violence\n[00:27.84] Bre...
2,Ice Ice Baby,Vanilla Ice,1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3XVozq1aeqsJwpXrEZrDJ9,aWNlLWljZS1iYWJ5LXZhbmlsbGEtaWNl,None,None,D,major,10B,116,4:14,72,79,98,58,0,0,10,4,-3 dB,"Yo VIP, let's kick it\nIce, ice baby\nIce, ice...","[00:12.88] Yo VIP, let's kick it\n[00:18.55] I..."
3,Smells Like Teen Spirit,Nirvana,1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5ghIJDpPoe3CfHMGu71E6T,c21lbGxzLWxpa2UtdGVlbi1zcGlyaXQtbmlydmFuYQ==,None,None,C#,major,3B,117,5:02,83,91,50,72,0,0,11,6,-5 dB,"Load up on guns, bring your friends\nIt's fun ...","[00:34.40] Load up on guns, bring your friends..."
4,Losing My Religion,R.E.M.,1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31AOj9sFz2gM0O3hMARRBx,bG9zaW5nLW15LXJlbGlnaW9uLXJlbQ==,None,None,A,minor,8A,126,4:28,88,86,67,80,18,0,10,3,-5 dB,"Oh, life is bigger\nIt's bigger than you\nAnd ...","[00:32.48] Oh, life is bigger\n[00:37.65] It's..."
5,Black or White,Michael Jackson,1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7EsjkelQuoUlJXEw7SeVV4,YmxhY2stb3Itd2hpdGUtbWljaGFlbC1qYWNrc29u,None,None,A,major,11B,115,4:16,77,90,52,87,17,3,7,9,-4 dB,Aaow!\n\nAaow!\n\nI took my baby on a Saturday...,[01:02.86] Aaow!\n[01:05.17] \n[01:11.45] Aaow...
6,I Will Always Love You,Whitney Houston,1992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4eHbdreAnSOrDDsFfc4Fpm,aS13aWxsLWFsd2F5cy1sb3ZlLXlvdS13aGl0bmV5LWhvdX...,None,None,E,major,12B,68,4:31,80,21,33,11,85,0,8,3,-13 dB,If I should stay\nI would only be in your way\...,[00:00.45] If I should stay\n[00:10.78] I woul...
7,Creep,Radiohead,1992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70LcF31zb1H0PyJoS1Sx1r,Y3JlZXAtcmFkaW9oZWFk,None,None,G,major,9B,92,3:59,93,43,52,10,1,0,13,4,-10 dB,When you were here before\nCouldn't look you i...,[00:18.98] When you were here before\n[00:23.8...
8,Baby Got Back,Sir Mix-a-Lot,1992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1SAkL1mYNJlaqnBQxVZrRl,YmFieS1nb3QtYmFjay1zaXItbWl4YWxvdA==,None,None,C#,major,3B,128,4:23,75,67,93,64,1,0,9,30,-11 dB,"Oh my God\nBecky, look at her butt\nIt's so bi...","[00:00.19] Oh my God\n[00:02.18] Becky, look a..."
9,What Is Love,Haddaway,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0OTO8ZF2YqFQVw9hnZylTd,d2hhdC1pcy1sb3ZlLTdxdW90LW1peC1oYWRkYXdheQ==,None,None,G,minor,6A,124,4:30,67,77,68,74,2,2,20,3,-8 dB,"What is love?\nOh, baby, don't hurt me\nDon't ...","[00:00.32] What is love?\n[00:01.81] Oh, baby,..."
10,C.R.E.A.M.,Wu-Tang Clan,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119c93MHjrDLJTApCVGpvx,Y3JlYW0tY2FzaC1ydWxlcy1ldmVyeXRoaW5nLWFyb3VuZC...,None,None,B,minor,10A,181,4:12,76,51,51,56,56,1,13,39,-12 dB,"What that nigga want, God?\nWord up, look out ...","[00:00.09] What that nigga want, God?\n[00:02...."
11,All That She Wants,Ace of Base,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6kWJvPfC4DgUpRsXKNa9z9,YWxsLXRoYXQtc2hlLXdhbnRzLWFjZS1vZi1iYXNl,None,None,B,major,1B,94,3:31,82,63,80,86,1,0,10,5,-10 dB,She leads a lonely life\nShe leads a lonely li...,[00:10.25] She leads a lonely life\n[00:15.41]...
12,Basket Case,Green Day,1994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6L89mwZXSOwYl76YXfX13s,YmFza2V0LWNhc2UtZ3JlZW4tZGF5,None,None,Eb,major,5B,85,3:02,86,94,44,78,0,0,9,6,-3 dB,Do you have the time to listen to me whine?\nA...,[00:16.13] Do you have the time to listen to m...
13,Black Hole Sun,Soundgarden,1994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2EoOZnxNgtmZaD8uUmz2nD,YmxhY2staG9sZS1zdW4tc291bmRnYXJkZW4=,None,None,F#,major,2B,105,5:19,80,83,35,15,0,0,8,4,-5 dB,In my eyes\nIndisposed\nIn disguises no one kn...,[00:16.54] In my eyes\n[00:18.78] Indisposed\n...
14,All I Want for Christmas Is You,Mariah Carey,1994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0bYg9bo50gSsH3LtXe2SQn,YWxsLWktd2FudC1mb3ItY2hyaXN0bWFzLWlzLXlvdS1tYX...,None,None,G,major,9B,150,4:02,75,63,34,35,16,0,7,4,-7 dB,I don't want a lot for Christmas\nThere is jus...,[00:06.34] I don't want a lot for Christmas\n[...
15,Wonderwall,Oasis,1995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7ygpwy2qP3NbrxVkHvUhXY,d29uZGVyd2FsbC1yZW1hc3RlcmVkLW9hc2lz,None,None,D,major,10B,174,4:19,80,89,38,43,0,0,19,4,-4 dB,Today is gonna be the day\nThat they're gonna ...,[00:38.31] Today is gonna be the day\n[00:40.6...
16,Gangsta's Paradise,"Coolio, L.V.",1995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1DIXPcTDzTj8ZMHt3PDt8p,Z2FuZ3N0YXgyN3MtcGFyYWRpc2UtY29vbGlvLWx2,None,None,Ab,major,4B,80,4:01,88,51,65,39,7,0,40,6,-10 dB,As I walk through the valley of the shadow of ...,[00:12.06] As I walk through the valley of the...
17,Waterfalls,TLC,1995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6qspW4YKycviDFjHBOaqUY,d2F0ZXJmYWxscy10bGM=,None,None,C#,major,3B,172,4:40,77,51,77,76,31,0,8,8,-7 dB,A lonely mother gazing out of her window\nStar...,[00:34.06] A lonely mother gazing out of her w...
18,Wannabe,Spice Girls,1996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1Je1IMUlBXcx1Fz0WE7oPT,d2FubmFiZS1zcGljZS1naXJscw==,None,None,B,major,1B,110,2:53,84,86,77,89,10,0,16,3,-6 dB,"Yo, I'll tell you what I want, what I really, ...","[00:04.24] Yo, I'll tell you what I want, what..."
19,California Love,"2Pac, Dr. Dre",1996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3ia3dJETSOllPsv3LJkE35,Y2FsaWZvcm5pYS1sb3ZlLW9yaWdpbmFsLXZlcnNpb24tMn...,None,None,G,major,9B,92,4:45,82,85,76,76,3,0,37,4,-3 dB,California love!\n\nCalifornia... knows how to...,[00:00.75] California love!\n[00:12.88] Califo...
20,Don't Speak,No Doubt,1996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6urCAbunOQI4bLhmGpX7iS,ZG9ueDI3dC1zcGVhay1uby1kb3VidA==,None,None,F,minor,4A,76,4:23,62,75,51,55,25,0,14,3,-5 dB,You and me\nWe used to be together\nEvery day ...,[00:06.48] You and me\n[00:09.50] We used to b...
21,My Heart Will Go On,Céline Dion,1997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33LC84JgLvK2KuW43MfaNq,bXktaGVhcnQtd2lsbC1nby1vbi1sb3ZlLXRoZW1lLWZyb2...,None,None,E,major,12B,99,4:40,75,28,43,4,73,0,12,3,-12 dB,"Every night in my dreams\nI see you, I feel yo...",[00:18.73] Every night in my dreams\n[00:23.88...
22,Bitter Sweet Symphony,The Verve,1997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57iDDD9N9tTWe75x6qhStw,Yml0dGVyLXN3ZWV0LXN5bXBob255LXJlbWFzdGVyZWQtMj...,None,None,A,major,11B,171,5:57,85,92,36,52,3,0,41,5,-6 dB,"'Cause it's a bitter sweet symphony, that's li...",[00:35.99] 'Cause it's a bitter sweet symphony...
23,Barbie Girl,Aqua,1997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5ZrDlcxIDZyjOzHdYW1ydr,YmFyYmllLWdpcmwtYXF1YQ==,None,None,C#,minor,12A,130,3:18,78,88,81,96,2,22,37,4,-11 dB,"Hiya, Barbie!\nHi, Ken!\nYou wanna go for a ri...","[00:04.02] Hiya, Barbie!\n[00:05.39] Hi, Ken!\..."
24,...Baby One More Time,Britney Spears,1998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3MjUtNVVq3C8Fn0MP3zhXa,YmFieS1vbmUtbW9yZS10aW1lLWJyaXRuZXktc3BlYXJz,None,None,C,minor,5A,93,3:31,86,70,76,91,20,0,44,3,-6 dB,"Oh, baby, baby\nOh, baby, baby\n\nOh, baby, ba...","[00:01.08] Oh, baby, baby\n[00:06.07] Oh, baby..."
25,The Boy Is Mine,"Brandy, Monica",1998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6sHsXIJoEN5JpdkGMQDJxt,dGhlLWJveS1pcy1taW5lLWJyYW5keS1tb25pY2E=,None,None,C#,minor,12A,93,4:55,78,71,70,76,54,0,32,4,-7 dB,"The boy is mine, the boy is mine\nThe boy is m...",None
26,I Don't Want to Miss a Thing,Aerosmith,1998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5qlJg0Wbj3sslxfwiaRNpq,aS1kb254Mjd0LXdhbnQtdG8tbWlzcy1hLXRoaW5nLWZyb2...,None,None,D,major,10B,121,4:59,77,66,38,14,17,0,25,3,-5 dB,I could stay awake just to hear you breathing\...,[00:30.21] I could stay awake just to hear you...
27,I Want It That Way,Backstreet Boys,1999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47BBI51FKFwOMlIiX6m8ya,aS13YW50LWl0LXRoYXQtd2F5LWJhY2tzdHJlZXQtYm95cw==,None,None,F#,minor,11A,99,3:33,86,69,69,48,26,0,15,3,-6 dB,a letra nao esta sincronizada com a musica,a letra nao esta sincronizada com a musica
28,No Scrubs,TLC,1999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1KGi9sZVMeszgZOWivFpxs,bm8tc2NydWJzLXRsYw==,None,None,G#,minor,1A,93,3:34,85,68,74,59,3,0,7,10,-4 dB,"Hmm, oh no\n\nA scrub is a guy that thinks he'...","[00:02.70] Hmm, oh no\n[00:10.27] A scrub is a..."
29,Smooth,"Santana, Rob Thomas",1999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2pX4FpOgwItRVPPUFdRcxA,c21vb3RoLWZlYXQtcm9iLXRob21hcy1zYW50YW5hLXJvYi...,None,None,A,major,11B,116,4:55,73,92,61,96,16,0,30,3,-4 dB,"Man, it's a hot one\nLike seven inches from th...","[00:18.00] Man, it's a hot one\n[00:20.93] Lik..."
30,Oops!... I Did It Again,Britney Spears,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6naxalmIoLFWR0siv8dnQQ,b29wc2ktZGlkLWl0LWFnYWluLWJyaXRuZXktc3BlYXJz,None,None,C#,minor,12A,95,3:31,83,83,75,89,30,0,36,4,-5 dB,"Mm, yeah\nYeah, yeah, yeah, yeah, yeah, yeah\n...",None
31,Bye Bye Bye,*NSYNC,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62bOmKYxYg7dhrC6gH9vFn,YnllLWJ5ZS1ieWUtbnN5bmM=,None,None,G#,minor,1A,173,3:20,81,93,61,86,3,0,8,5,-5 dB,"Hey, hey\nBye, bye, bye\nBye, bye\nBye, bye\n\...","[00:07.76] Hey, hey\n[00:10.11] Bye, bye, bye\..."
32,Stan,"Eminem, Dido",2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3UmaczJpikHgJFyBTAJVoz,c3Rhbi1lbWluZW0tZGlkbw==,None,None,F#,minor,11A,80,6:44,83,77,78,51,4,0,52,24,-4 dB,"My tea's gone cold, I'm wondering why I got ou...","[00:01.58] My tea's gone cold, I'm wondering w..."
33,In the End,Linkin Park,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60a0Rd6pjrkxjPbaKzXjfq,aW4tdGhlLWVuZC1saW5raW4tcGFyaw==,None,None,D#,minor,2A,105,3:37,91,86,56,40,1,0,21,6,-6 dB,as letras nao estao sincronizadas com a musica,as letras nao estao sincronizadas com a musica
34,How You Remind Me,Nickelback,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0gmbgwZ8iqyMPmXefof8Yf,aG93LXlvdS1yZW1pbmQtbWUtbmlja2VsYmFjaw==,None,None,Bb,major,6B,172,3:44,88,76,45,54,0,0,10,3,-5 dB,Never made it as a wise man\nI couldn't cut it...,[00:00.46] Never made it as a wise man\n[00:03...
35,Fallin',Alicia Keys,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0KQx6HOpJueiSkztcS0r7D,ZmFsbGlueDI3LWFsaWNpYS1rZXlz,None,None,B,minor,10A,96,3:30,81,61,65,48,26,0,23,4,-8 dB,I keep on fallin' in\nAnd out of love with you...,[00:00.03] I keep on fallin' in\n[00:05.86] \n...
36,Lose Yourself,Eminem,2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5Z01UMMf7V1o0MzF86s6WJ,bG9zZS15b3Vyc2VsZi1lbWluZW0=,None,None,D,major,10B,171,5:26,81,74,69,6,1,0,36,26,-5 dB,"Look\nIf you had one shot, or one opportunity\...",[00:34.30] Look\n[00:37.19] If you had one sho...
37,Complicated,Avril Lavigne,2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5xEM5hIgJ1jjgcEBfpkt2F,Y29tcGxpY2F0ZWQtYXZyaWwtbGF2aWduZQ==,None,None,F,major,7B,78,4:05,86,78,59,43,6,0,30,5,-6 dB,"Uh-huh, life's like this\nUh-huh, uh-huh, that...","[00:02.04] Uh-huh, life's like this\n[00:06.78..."
38,Hot in Herre,Nelly,2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04KTF78FFg8sOHC1BADqbY,aG90LWluLWhlcnJlLW5lbGx5,None,None,B,minor,10A,107,3:48,80,74,96,91,20,0,6,12,-5 dB,It's hot in\nSo hot in here\nSo hot in (ah)\nO...,[00:01.73] It's hot in\n[00:04.52] So hot in h...
39,Crazy in Love,"Beyoncé, JAY-Z",2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5IVuqXILoxVWvWEPm82Jxr,Y3JhenktaW4tbG92ZS1mZWF0LWpheXotYmV5b25jLWpheg==,None,None,D,minor,7A,99,3:56,81,77,65,68,0,0,7,23,-7 dB,Yes (woo! Ow!)\nIt's so crazy right now\nMost ...,[00:01.94] Yes (woo! Ow!)\n[00:03.72] It's so ...
40,Hey Ya!,Outkast,2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2PpruBYCo4H7WOBJ7Q2EwM,aGV5LXlhLW91dGthc3Q=,None,None,E,minor,9A,80,3:55,84,97,73,97,10,0,17,7,-2 dB,"One, two, three, uh!\n\nMy baby don't mess aro...","[00:00.08] One, two, three, uh!\n[00:01.54] My..."
41,In da Club,50 Cent,2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4RY96Asd9IefaL3X4LOLZ8,aW4tZGEtY2x1Yi01MC1jZW50,None,None,F#,minor,11A,90,3:13,78,72,90,81,26,0,7,35,-3 dB,"Go, go, go, go, go, go\nGo, shorty, it's your ...","[00:01.47] Go, go, go, go, go, go\n[00:05.37] ..."
42,Yeah!,"Usher, Lil Jon, Ludacris",2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5rb9QrpfcKFHM1EUbSIurX,eWVhaC1mZWF0LWxpbC1qb24tYW1wLWx1ZGFjcmlzLXVzaG...,None,None,D,major,10B,105,4:10,87,79,89,58,2,0,4,11,-5 dB,"Peace up, A-Town down\nYeah! Okay\nUsher\nLil ...",None
43,Mr. Brightside,The Killers,2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,003vvx7Niy0yvhvHt4a68B,bXItYnJpZ2h0c2lkZS10aGUta2lsbGVycw==,None,None,C#,major,3B,148,3:43,91,91,35,24,0,0,10,7,-5 dB,I'm coming out of my cage and I've been doing ...,[00:06.40] I'm coming out of my cage and I've ...
44,Toxic,Britney Spears,2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6I9VzXrHxO9rA9A5euc8Ak,dG94aWMtYnJpdG5leS1zcGVhcnM=,None,None,F,minor,4A,143,3:19,86,84,77,92,2,3,24,11,-4 dB,"Baby, can't you see I'm calling?\nA guy like y...","[00:13.84] Baby, can't you see I'm calling?\n[..."
45,Gold Digger,"Kanye West, Jamie Foxx",2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1PS1QMdUqOal0ai3Gt7sDQ,Z29sZC1kaWdnZXIta2FueWUtd2VzdC1qYW1pZS1mb3h4,None,None,C#,minor,12A,93,3:28,82,70,63,62,2,0,6,35,-6 dB,"She take my money when I'm in need\nYeah, she'...",[00:00.03] She take my money when I'm in need\...
46,We Belong Together,Mariah Carey,2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3LmvfNUQtglbTrydsdIqFU,d2UtYmVsb25nLXRvZ2V0aGVyLW1hcmlhaC1jYXJleQ==,None,None,C,major,8B,140,3:21,73,47,83,77,3,0,9,6,-8 dB,Sweet love yeah\nI didn't mean it when I said ...,[00:17.53] Sweet love yeah\n[00:21.55] I didn'...
47,Feel Good Inc.,Gorillaz,2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0d28khcov6AiegSCpG5TuT,ZmVlbC1nb29kLWluYy1nb3JpbGxhei1kZS1sYS1zb3Vs,None,None,F#,major,2B,139,3:43,92,71,82,77,1,0,61,18,-7 dB,"Feel good\nSha, sha-ba-da, sha-ba-da-ca, feel ...","[00:21.73] Feel good\n[00:24.34] Sha, sha-ba-d..."
48,Hips Don't Lie,"Shakira, Wyclef Jean",2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3d0WouFnFmr0K3kjeza3fF,aGlwcy1kb254Mjd0LWxpZS1mZWF0LXd5Y2xlZi1qZWFuLX...,None,None,A#,minor,3A,100,3:40,89,82,78,76,28,0,36,7,-6 dB,Ladies up in here tonight\nNo fighting\nWe got...,[00:00.04] Ladies up in here tonight\n[00:02.1...
49,SexyBack,Justin Timberlake,2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0O45fw2L5vsWpdsOdXwNAR,c2V4eWJhY2stZmVhdC10aW1iYWxhbmQtanVzdGluLXRpbW...,None,None,G,minor,6A,117,4:03,87,58,97,96,6,0,5,8,-6 dB,I'm bringing sexy back (yeah)\nThem other boys...,[00:15.72] I'm bringing sexy back (yeah)\n[00:...
50,Crazy,Gnarls Barkley,2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6o1l9I0faXJN2iqulHrdCQ,Y3JhenktZ25hcmxzLWJhcmtsZXktY2VlbG8tZ3JlZW4tZG...,None,None,Ab,major,4B,112,3:02,77,74,84,61,2,6,8,3,-2 dB,"I remember when\nI remember, I remember when I...",[00:02.58] I remember when\n[00:04.03] I remem...
51,Umbrella,"Rihanna, JAY-Z",2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2yPoXCs7BSIUrucMdK5PzV,dW1icmVsbGEtcmloYW5uYS1qYXo=,None,None,C#,major,3B,174,4:36,86,83,59,58,1,0,4,12,-5 dB,"Uh-huh, uh-huh (yeah, Rihanna)\nUh-huh, uh-huh...","[00:01.20] Uh-huh, uh-huh (yeah, Rihanna)\n[00..."
52,Stronger,Kanye West,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0j2T0R9dR9qdJYsB7ciXhf,c3Ryb25nZXIta2FueWUtd2VzdA==,None,None,C#,major,3B,104,5:12,86,72,62,50,1,0,41,14,-8 dB,"Work it, make it, do it, makes us\nHarder, bet...","[00:01.57] Work it, make it, do it, makes us\n..."
53,Crank That (Soulja Boy),Soulja Boy,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66TRwr5uJwPt15mfFkzhbi,Y3JhbmstdGhhdC1zb3VsamEtYm95LXNvdWxqYS1ib3k=,None,None,C,major,8B,140,3:42,78,74,73,80,51,0,5,9,-2 dB,"Yuu\nSoulja Boy Tell 'Em\nAy, I got this new d...",[00:00.24] Yuu\n[00:02.52] Soulja Boy Tell 'Em...
54,Viva La Vida,Coldplay,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1mea3bSkSGXuIRvnydlB5b,dml2YS1sYS12aWRhLWNvbGRwbGF5,None,None,F,minor,4A,138,4:02,89,62,49,42,10,0,11,3,-7 dB,I used to rule the world\nSeas would rise when...,[00:13.10] I used to rule the world\n[00:16.97...
55,Single Ladies (Put a Ring on It),Beyoncé,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2ZBNclC5wm4GtiWaeh0DMx,c2luZ2xlLWxhZGllcy1wdXQtYS1yaW5nLW9uLWl0LWJleW...,None,None,C#,major,3B,193,3:13,69,58,43,27,4,0,19,30,-5 dB,"All the single ladies, all the single ladies\n...","[00:01.80] All the single ladies, all the sing..."
56,Poker Face,Lady Gaga,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5R8dQOPq8haW94K7mgERlO,cG9rZXItZmFjZS1sYWR5LWdhZ2E=,None,None,E,major,12B,119,3:57,82,81,85,77,12,0,12,8,-5 dB,Mum-mum-mum-mah\nMum-mum-mum-mah\nMum-mum-mum-...,[00:01.05] Mum-mum-mum-mah\n[00:11.54] Mum-mum...
57,I Gotta Feeling,Black Eyed Peas,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2H1047e0oMSj10dgp7p2VG,aS1nb3R0YS1mZWVsaW5nLWJsYWNrLWV5ZWQtcGVhcw==,None,None,C,major,8B,128,4:49,80,77,74,61,9,0,51,3,-6 dB,I got a feeling\nThat tonight's gonna be a goo...,[00:29.35] I got a feeling\n[00:33.40] That to...
58,Bad Romance,Lady Gaga,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0SiywuOBRcynK0uKGWdCnn,YmFkLXJvbWFuY2UtbGFkeS1nYWdh,None,None,C,major,8B,119,4:54,51,92,69,71,0,0,9,4,-4 dB,"Oh-oh-oh-oh-oh, oh-oh-oh-oh, oh-oh-oh\nCaught ...","[00:00.17] Oh-oh-oh-oh-oh, oh-oh-oh-oh, oh-oh-..."
59,Tik Tok,Kesha,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0HPD5WQqrq7wPWR7P7Dw1i,dGlrLXRvay1rZXNoYQ==,None,None,D,minor,7A,120,3:20,87,84,76,71,10,0,29,14,-3 dB,Wake up in the morning feelin' like P. Diddy (...,[00:08.79] Wake up in the morning feelin' like...
60,Rolling in the Deep,Adele,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1c8gk2PeTE04A1pIDH9YMk,cm9sbGluZy1pbi10aGUtZGVlcC1hZGVsZQ==,None,None,Ab,major,4B,105,3:48,78,77,73,51,14,0,5,3,-5 dB,There's a fire starting in my heart\nReaching ...,[00:05.10] There's a fire starting in my heart...
61,Teenage Dream,Katy Perry,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5jzKL4BDMClWqRguW5qZvh,dGVlbmFnZS1kcmVhbS1rYXR5LXBlcnJ5,None,None,Bb,major,6B,120,3:48,75,80,72,59,2,0,13,4,-5 dB,You think I'm pretty without any makeup on\nYo...,[00:04.90] You think I'm pretty without any ma...

In [9]:
music_data.to_csv('C:/Users/maxph/OneDrive/Desktop/CLARIFY/DataForOptimizingHitPotential.csv', index=False)
print("Complete! Lyrics added and saved.")

Complete! Lyrics added and saved.